/*
sdk 1.2.4 min
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(h){var y=0;return function(){return y<h.length?{done:!1,value:h[y++]}:{done:!0}}};$jscomp.arrayIterator=function(h){return{next:$jscomp.arrayIteratorImpl(h)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(h,y,B){if(h==Array.prototype||h==Object.prototype)return h;h[y]=B.value;return h};$jscomp.getGlobal=function(h){h=["object"==typeof globalThis&&globalThis,h,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var y=0;y<h.length;++y){var B=h[y];if(B&&B.Math==Math)return B}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(h,y){var B=$jscomp.propertyToPolyfillSymbol[y];if(null==B)return h[y];B=h[B];return void 0!==B?B:h[y]};
$jscomp.polyfill=function(h,y,B,x){y&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(h,y,B,x):$jscomp.polyfillUnisolated(h,y,B,x))};$jscomp.polyfillUnisolated=function(h,y,B,x){B=$jscomp.global;h=h.split(".");for(x=0;x<h.length-1;x++){var D=h[x];if(!(D in B))return;B=B[D]}h=h[h.length-1];x=B[h];y=y(x);y!=x&&null!=y&&$jscomp.defineProperty(B,h,{configurable:!0,writable:!0,value:y})};
$jscomp.polyfillIsolated=function(h,y,B,x){var D=h.split(".");h=1===D.length;x=D[0];x=!h&&x in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var F=0;F<D.length-1;F++){var T=D[F];if(!(T in x))return;x=x[T]}D=D[D.length-1];B=$jscomp.IS_SYMBOL_NATIVE&&"es6"===B?x[D]:null;y=y(B);null!=y&&(h?$jscomp.defineProperty($jscomp.polyfills,D,{configurable:!0,writable:!0,value:y}):y!==B&&($jscomp.propertyToPolyfillSymbol[D]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(D):$jscomp.POLYFILL_PREFIX+D,D=
$jscomp.propertyToPolyfillSymbol[D],$jscomp.defineProperty(x,D,{configurable:!0,writable:!0,value:y})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(h){if(h)return h;var y=function(D,F){this.$jscomp$symbol$id_=D;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:F})};y.prototype.toString=function(){return this.$jscomp$symbol$id_};var B=0,x=function(D){if(this instanceof x)throw new TypeError("Symbol is not a constructor");return new y("jscomp_symbol_"+(D||"")+"_"+B++,D)};return x},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(h){if(h)return h;h=Symbol("Symbol.iterator");for(var y="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),B=0;B<y.length;B++){var x=$jscomp.global[y[B]];"function"===typeof x&&"function"!=typeof x.prototype[h]&&$jscomp.defineProperty(x.prototype,h,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return h},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(h){h={next:h};h[Symbol.iterator]=function(){return this};return h};
(function(){"function"!=typeof Object.assign&&Object.defineProperty(Object,"assign",{value:function(h,y){if(null==h)throw new TypeError("Cannot convert undefined or null to object");for(var B=Object(h),x=1;x<arguments.length;x++){var D=arguments[x];if(null!=D)for(var F in D)Object.prototype.hasOwnProperty.call(D,F)&&(B[F]=D[F])}return B},writable:!0,configurable:!0});Array.from||(Array.from=function(){var h=Object.prototype.toString,y=function(x){return"function"===typeof x||"[object Function]"===
h.call(x)},B=Math.pow(2,53)-1;return function(x){var D=Object(x);if(null==x)throw new TypeError("Array.from requires an array-like object - not null or undefined");var F=1<arguments.length?arguments[1]:void 0,T;if("undefined"!==typeof F){if(!y(F))throw new TypeError("Array.from: when provided, the second argument must be a function");2<arguments.length&&(T=arguments[2])}var Q=Number(D.length);Q=isNaN(Q)?0:0!==Q&&isFinite(Q)?(0<Q?1:-1)*Math.floor(Math.abs(Q)):Q;Q=Math.min(Math.max(Q,0),B);for(var aa=
y(this)?Object(new this(Q)):Array(Q),V=0,ha;V<Q;)ha=D[V],aa[V]=F?"undefined"===typeof T?F(ha,V):F.call(T,ha,V):ha,V+=1;aa.length=Q;return aa}}());Array.prototype.find||Object.defineProperty(Array.prototype,"find",{value:function(h,y){if(null==this)throw new TypeError('"this" is null or not defined');var B=Object(this),x=B.length>>>0;if("function"!==typeof h)throw new TypeError("predicate must be a function");for(var D=0;D<x;){var F=B[D];if(h.call(y,F,D,B))return F;D++}}});Number.isNaN=Number.isNaN||
function(h){return"number"===typeof h&&isNaN(h)};String.prototype.endsWith||(String.prototype.endsWith=function(h,y){if(void 0===y||y>this.length)y=this.length;return this.substring(y-h.length,y)===h})})();
(function(){var h,y=function(B){return"function"==typeof window.onshow&&window.onshow()};/iPhone|iPod|iPad/i.test(navigator.userAgent)&&window.setInterval(function(B){B=Math.floor((new Date).getTime()/1E3);"number"==typeof h&&1<B-h&&y();h=B},1E3);"complete"===document.readyState||"loading"!==document.readyState&&!document.documentElement.doScroll?y():document.addEventListener("DOMContentLoaded",y)})();
var rrweb=function(h){function y(a){var b="function"===typeof Symbol&&Symbol.iterator,c=b&&a[b],f=0;if(c)return c.call(a);if(a&&"number"===typeof a.length)return{next:function(){a&&f>=a.length&&(a=void 0);return{value:a&&a[f++],done:!a}}};throw new TypeError(b?"Object is not iterable.":"Symbol.iterator is not defined.");}function B(a,b){var c="function"===typeof Symbol&&a[Symbol.iterator];if(!c)return a;a=c.call(a);var f,d=[];try{for(;(void 0===b||0<b--)&&!(f=a.next()).done;)d.push(f.value)}catch(l){var e=
{error:l}}finally{try{f&&!f.done&&(c=a["return"])&&c.call(a)}finally{if(e)throw e.error;}}return d}function x(){for(var a=[],b=0;b<arguments.length;b++)a=a.concat(B(arguments[b]));return a}function D(a){a=a.toLowerCase().trim();return bb.test(a)?"div":a}function F(a){try{var b=a.rules||a.cssRules;return b?Array.from(b).map(T).join(""):null}catch(c){return null}}function T(a){return"styleSheet"in a?F(a.styleSheet)||"":a.cssText}function Q(a,b){return(a||"").replace(cb,function(c,f,d,e,l,k){d=d||l||
k;f=f||e||"";if(!d)return c;if(!db.test(d)||eb.test(d))return"url("+f+d+f+")";if("/"===d[0])return c=-1<b.indexOf("//")?b.split("/").slice(0,3).join("/"):b.split("/")[0],c=c.split("?")[0],"url("+f+(c+d)+f+")";c=b.split("/");e=d.split("/");c.pop();for(d=0;d<e.length;d++)l=e[d],"."!==l&&(".."===l?c.pop():c.push(l));return"url("+f+c.join("/")+f+")"})}function aa(a,b){return""===b.trim()?b:b.split(",").map(function(c){c=c.trimLeft().trimRight().split(" ");if(2===c.length){var f=V(a,c[0]);return f+" "+
c[1]}return 1===c.length?(f=V(a,c[0]),""+f):""}).join(", ")}function V(a,b){if(!b||""===b.trim())return b;a=a.createElement("a");a.href=b;return a.href}function ha(a,b,c){return"src"===b||"href"===b&&c?V(a,c):"srcset"===b&&c?aa(a,c):"style"===b&&c?Q(c,location.href):c}function ta(a,b,c){if("string"===typeof b){if(a.classList.contains(b))return!0}else a.classList.forEach(function(f){if(b.test(f))return!0});return c?a.matches(c):!1}function ua(a,b){var c=b.doc,f=b.blockClass,d=b.blockSelector,e=b.inlineStylesheet,
l=b.maskInputOptions;l=void 0===l?{}:l;b=b.recordCanvas;switch(a.nodeType){case a.DOCUMENT_NODE:return{type:N.Document,childNodes:[]};case a.DOCUMENT_TYPE_NODE:return{type:N.DocumentType,name:a.name,publicId:a.publicId,systemId:a.systemId};case a.ELEMENT_NODE:f=ta(a,f,d);d=D(a.tagName);for(var k={},m=0,r=Array.from(a.attributes);m<r.length;m++){var v=r[m],p=v.name;v=v.value;k[p]=ha(c,p,v)}"link"===d&&e&&(c=Array.from(c.styleSheets).find(function(u){return u.href===a.href}),e=F(c))&&(delete k.rel,
delete k.href,k._cssText=Q(e,c.href));"style"===d&&a.sheet&&!(a.innerText||a.textContent||"").trim().length&&(e=F(a.sheet))&&(k._cssText=Q(e,location.href));if("input"===d||"textarea"===d||"select"===d)v=a.value,"radio"!==k.type&&"checkbox"!==k.type&&"submit"!==k.type&&"button"!==k.type&&v?k.value=l[k.type]||l[d]?"*".repeat(v.length):v:a.checked&&(k.checked=a.checked);"option"===d&&k.value===a.parentElement.value&&(k.selected=a.selected);"canvas"===d&&b&&(k.rr_dataURL=a.toDataURL());if("audio"===
d||"video"===d)k.rr_mediaState=a.paused?"paused":"played";a.scrollLeft&&(k.rr_scrollLeft=a.scrollLeft);a.scrollTop&&(k.rr_scrollTop=a.scrollTop);f&&(l=a.getBoundingClientRect(),k={class:k.class,rr_width:l.width+"px",rr_height:l.height+"px"});return{type:N.Element,tagName:d,attributes:k,childNodes:[],isSVG:"svg"===a.tagName||a instanceof SVGElement||void 0,needBlock:f};case a.TEXT_NODE:return l=a.parentNode&&a.parentNode.tagName,c=a.textContent,(e="STYLE"===l?!0:void 0)&&c&&(c=Q(c,location.href)),
"SCRIPT"===l&&(c="SCRIPT_PLACEHOLDER"),{type:N.Text,textContent:c||"",isStyle:e};case a.CDATA_SECTION_NODE:return{type:N.CDATA,textContent:""};case a.COMMENT_NODE:return{type:N.Comment,textContent:a.textContent||""};default:return!1}}function J(a){return void 0===a?"":a.toLowerCase()}function z(a,b){var c=b.doc,f=b.map,d=b.blockClass,e=b.blockSelector,l=b.skipChild;l=void 0===l?!1:l;var k=b.inlineStylesheet;k=void 0===k?!0:k;var m=b.maskInputOptions;m=void 0===m?{}:m;var r=b.slimDOMOptions,v=b.recordCanvas;
v=void 0===v?!1:v;b=b.preserveWhiteSpace;b=void 0===b?!0:b;var p=ua(a,{doc:c,blockClass:d,blockSelector:e,inlineStylesheet:k,maskInputOptions:m,recordCanvas:v});if(!p)return console.warn(a,"not serialized"),null;var u="__sn"in a?a.__sn.id:r.comment&&p.type===N.Comment||p.type===N.Element&&(r.script&&("script"===p.tagName||"link"===p.tagName&&"preload"===p.attributes.rel&&"script"===p.attributes.as)||r.headFavicon&&("link"===p.tagName&&"shortcut icon"===p.attributes.rel||"meta"===p.tagName&&(J(p.attributes.name).match(/^msapplication-tile(image|color)$/)||
"application-name"===J(p.attributes.name)||"icon"===J(p.attributes.rel)||"apple-touch-icon"===J(p.attributes.rel)||"shortcut icon"===J(p.attributes.rel)))||"meta"===p.tagName&&(r.headMetaDescKeywords&&J(p.attributes.name).match(/^description|keywords$/)||r.headMetaSocial&&(J(p.attributes.property).match(/^(og|twitter|fb):/)||J(p.attributes.name).match(/^(og|twitter):/)||"pinterest"===J(p.attributes.name))||r.headMetaRobots&&("robots"===J(p.attributes.name)||"googlebot"===J(p.attributes.name)||"bingbot"===
J(p.attributes.name))||r.headMetaHttpEquiv&&void 0!==p.attributes["http-equiv"]||r.headMetaAuthorship&&("author"===J(p.attributes.name)||"generator"===J(p.attributes.name)||"framework"===J(p.attributes.name)||"publisher"===J(p.attributes.name)||"progid"===J(p.attributes.name)||J(p.attributes.property).match(/^article:/)||J(p.attributes.property).match(/^product:/))||r.headMetaVerification&&("google-site-verification"===J(p.attributes.name)||"yandex-verification"===J(p.attributes.name)||"csrf-token"===
J(p.attributes.name)||"p:domain_verify"===J(p.attributes.name)||"verify-v1"===J(p.attributes.name)||"verification"===J(p.attributes.name)||"shopify-checkout-api-token"===J(p.attributes.name))))||!b&&p.type===N.Text&&!p.isStyle&&!p.textContent.replace(/^\s+|\s+$/gm,"").length?-2:fb++;var g=Object.assign(p,{id:u});a.__sn=g;if(-2===u)return null;f[u]=a;u=!l;g.type===N.Element&&(u=u&&!g.needBlock,delete g.needBlock);if((g.type===N.Document||g.type===N.Element)&&u)for(r.headWhitespace&&p.type===N.Element&&
"head"===p.tagName&&(b=!1),p=0,a=Array.from(a.childNodes);p<a.length;p++)(u=z(a[p],{doc:c,map:f,blockClass:d,blockSelector:e,skipChild:l,inlineStylesheet:k,maskInputOptions:m,slimDOMOptions:r,recordCanvas:v,preserveWhiteSpace:b}))&&g.childNodes.push(u);return g}function K(a,b){function c(q){var w=q.match(/\n/g);w&&(L+=w.length);w=q.lastIndexOf("\n");G=-1===w?G+q.length:q.length-w}function f(){var q={line:L,column:G};return function(w){w.position=new O(q);m(/^\s*/);return w}}function d(q){var w=Error(b.source+
":"+L+":"+G+": "+q);w.reason=q;w.filename=b.source;w.line=L;w.column=G;w.source=a;if(b.silent)ba.push(w);else throw w;}function e(){return m(/^{\s*/)}function l(){return m(/^}/)}function k(){var q,w=[];m(/^\s*/);for(r(w);a.length&&"}"!==a.charAt(0)&&(q=E()||H());)!1!==q&&(w.push(q),r(w));return w}function m(q){if(q=q.exec(a)){var w=q[0];c(w);a=a.slice(w.length);return q}}function r(q){void 0===q&&(q=[]);for(var w;w=v();)!1!==w&&q.push(w),v();return q}function v(){var q=f();if("/"===a.charAt(0)&&"*"===
a.charAt(1)){for(var w=2;""!==a.charAt(w)&&("*"!==a.charAt(w)||"/"!==a.charAt(w+1));)++w;w+=2;if(""===a.charAt(w-1))return d("End of comment missing");var I=a.slice(2,w-2);G+=2;c(I);a=a.slice(w);G+=2;return q({type:"comment",comment:I})}}function p(){var q=m(/^([^{]+)/);if(q)return M(q[0]).replace(/\/\*([^*]|[\r\n]|(\*+([^*/]|[\r\n])))*\*\/+/g,"").replace(/"(?:\\"|[^"])*"|'(?:\\'|[^'])*'/g,function(w){return w.replace(/,/g,"\u200c")}).split(/\s*(?![^(]*\)),\s*/).map(function(w){return w.replace(/\u200C/g,
",")})}function u(){var q=f(),w=m(/^(\*?[-#\/\*\\\w]+(\[[0-9a-z_-]+\])?)\s*/);if(w){w=M(w[0]);if(!m(/^:\s*/))return d("property missing ':'");var I=m(/^((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^\)]*?\)|[^};])+)/);q=q({type:"declaration",property:w.replace(Ka,""),value:I?M(I[0]).replace(Ka,""):""});m(/^[;\s]*/);return q}}function g(){var q=[];if(!e())return d("missing '{'");r(q);for(var w;w=u();)!1!==w&&(q.push(w),r(q)),u();return l()?q:d("missing '}'")}function n(){for(var q,w=[],I=f();q=m(/^((\d+\.\d+|\.\d+|\d+)%?|[a-z]+)\s*/);)w.push(q[1]),
m(/^,\s*/);if(w.length)return I({type:"keyframe",values:w,declarations:g()})}function t(){var q=f(),w=m(/^@([-\w]+)?keyframes\s*/);if(w){var I=w[1];w=m(/^([-\w]+)\s*/);if(!w)return d("@keyframes missing name");w=w[1];if(!e())return d("@keyframes missing '{'");for(var Y,ca=r();Y=n();)ca.push(Y),ca=ca.concat(r());return l()?q({type:"keyframes",name:w,vendor:I,keyframes:ca}):d("@keyframes missing '}'")}}function A(q){var w=new RegExp("^@"+q+"\\s*([^;]+);");return function(){var I=f(),Y=m(w);if(Y){var ca=
{type:q};ca[q]=Y[1].trim();return I(ca)}}}function E(){if("@"===a[0]){var q;if(!(q=t())){q=f();var w=m(/^@media *([^{]+)/);if(w)if(w=M(w[1]),e()){var I=r().concat(k());q=l()?q({type:"media",media:w,rules:I}):d("@media missing '}'")}else q=d("@media missing '{'");else q=void 0}q||(q=f(),q=(w=m(/^@custom-media\s+(--[^\s]+)\s*([^{;]+);/))?q({type:"custom-media",name:M(w[1]),media:M(w[2])}):void 0);q||(q=f(),(w=m(/^@supports *([^{]+)/))?(w=M(w[1]),e()?(I=r().concat(k()),q=l()?q({type:"supports",supports:w,
rules:I}):d("@supports missing '}'")):q=d("@supports missing '{'")):q=void 0);if(!(q=q||ia()||Z()||ka()))if(q=f(),I=m(/^@([-\w]+)?document *([^{]+)/))if(w=M(I[1]),I=M(I[2]),e()){var Y=r().concat(k());q=l()?q({type:"document",document:I,vendor:w,rules:Y}):d("@document missing '}'")}else q=d("@document missing '{'");else q=void 0;if(!q)if(q=f(),m(/^@page */))if(w=p()||[],e()){for(I=r();Y=u();)I.push(Y),I=I.concat(r());q=l()?q({type:"page",selectors:w,declarations:I}):d("@page missing '}'")}else q=d("@page missing '{'");
else q=void 0;q||(q=f(),m(/^@host\s*/)?e()?(w=r().concat(k()),q=l()?q({type:"host",rules:w}):d("@host missing '}'")):q=d("@host missing '{'"):q=void 0);if(!q)if(q=f(),m(/^@font-face\s*/))if(e()){for(w=r();I=u();)w.push(I),w=w.concat(r());q=l()?q({type:"font-face",declarations:w}):d("@font-face missing '}'")}else q=d("@font-face missing '{'");else q=void 0;return q}}function H(){var q=f(),w=p();if(!w)return d("selector missing");r();return q({type:"rule",selectors:w,declarations:g()})}void 0===b&&
(b={});var L=1,G=1,O=function(){return function(q){this.start=q;this.end={line:L,column:G};this.source=b.source}}();O.prototype.content=a;var ba=[],ia=A("import"),Z=A("charset"),ka=A("namespace");return W(function(){var q=k();return{type:"stylesheet",stylesheet:{source:b.source,rules:q,parsingErrors:ba}}}())}function M(a){return a?a.replace(/^\s+|\s+$/g,""):""}function W(a,b){for(var c=a&&"string"===typeof a.type,f=c?a:b,d=0,e=Object.keys(a);d<e.length;d++){var l=a[e[d]];Array.isArray(l)?l.forEach(function(k){W(k,
f)}):l&&"object"===typeof l&&W(l,f)}c&&Object.defineProperty(a,"parent",{configurable:!0,writable:!0,enumerable:!1,value:b||null});return a}function da(a){var b=La[a.tagName]?La[a.tagName]:a.tagName;"link"===b&&a.attributes._cssText&&(b="style");return b}function R(a){var b=K(a,{silent:!0});if(!b.stylesheet)return a;b.stylesheet.rules.forEach(function(c){"selectors"in c&&(c.selectors||[]).forEach(function(f){if(Ma.test(f)){var d=f.replace(Ma,"$1.\\:hover");a=a.replace(f,f+", "+d)}})});return a}function gb(a,
b){var c=b.doc,f=b.hackCss;switch(a.type){case N.Document:return c.implementation.createDocument(null,"",null);case N.DocumentType:return c.implementation.createDocumentType(a.name||"html",a.publicId,a.systemId);case N.Element:var d=da(a);var e=a.isSVG?c.createElementNS("http://www.w3.org/2000/svg",d):c.createElement(d);b=function(k){if(!a.attributes.hasOwnProperty(k))return"continue";var m=a.attributes[k];m="boolean"===typeof m||"number"===typeof m?"":m;if(k.startsWith("rr_")){if("canvas"===d&&"rr_dataURL"===
k){var r=document.createElement("img");r.src=m;r.onload=function(){var u=e.getContext("2d");u&&u.drawImage(r,0,0,r.width,r.height)}}"rr_width"===k&&(e.style.width=m);"rr_height"===k&&(e.style.height=m);if("rr_mediaState"===k)switch(m){case "played":e.play();case "paused":e.pause()}}else{var v="textarea"===d&&"value"===k,p="style"===d&&"_cssText"===k;p&&f&&(m=R(m));if(v||p){k=c.createTextNode(m);m=0;for(v=Array.from(e.childNodes);m<v.length;m++)p=v[m],p.nodeType===e.TEXT_NODE&&e.removeChild(p);e.appendChild(k);
return"continue"}if("iframe"===d&&"src"===k)return"continue";try{a.isSVG&&"xlink:href"===k?e.setAttributeNS("http://www.w3.org/1999/xlink",k,m):"onload"===k||"onclick"===k||"onmouse"===k.substring(0,7)?e.setAttribute("_"+k,m):e.setAttribute(k,m)}catch(u){}}};for(var l in a.attributes)b(l);return e;case N.Text:return c.createTextNode(a.isStyle&&f?R(a.textContent):a.textContent);case N.CDATA:return c.createCDATASection(a.textContent);case N.Comment:return c.createComment(a.textContent);default:return null}}
function ya(a,b){var c=b.doc,f=b.map,d=b.skipChild,e=void 0===d?!1:d;b=b.hackCss;b=void 0===b?!0:b;d=gb(a,{doc:c,hackCss:b});if(!d)return null;a.type===N.Document&&(c.close(),c.open(),d=c);d.__sn=a;f[a.id]=d;if((a.type===N.Document||a.type===N.Element)&&!e)for(e=0,a=a.childNodes;e<a.length;e++){var l=a[e],k=ya(l,{doc:c,map:f,skipChild:!1,hackCss:b});k?d.appendChild(k):console.warn("Failed to rebuild",l)}return d}function hb(a,b){for(var c in a)a[c]&&b(a[c])}function ib(a,b){var c=b.onVisit,f=b.hackCss,
d={};a=ya(a,{doc:b.doc,map:d,skipChild:!1,hackCss:void 0===f?!0:f});hb(d,function(e){c&&c(e);var l=e.__sn;if(l.type===N.Element)for(var k in l.attributes)if(l.attributes.hasOwnProperty(k)&&k.startsWith("rr_")){var m=l.attributes[k];"rr_scrollLeft"===k&&(e.scrollLeft=m);"rr_scrollTop"===k&&(e.scrollTop=m)}});return[a,d]}function ea(a,b,c){void 0===c&&(c=document);var f={capture:!0,passive:!0};c.addEventListener(a,b,f);return function(){return c.removeEventListener(a,b,f)}}function ra(a,b,c){void 0===
c&&(c={});var f=null,d=0;return function(e){var l=Date.now();d||!1!==c.leading||(d=l);var k=b-(l-d),m=this,r=arguments;0>=k||k>b?(f&&(window.clearTimeout(f),f=null),d=l,a.apply(m,r)):f||!1===c.trailing||(f=window.setTimeout(function(){d=!1===c.leading?0:Date.now();f=null;a.apply(m,r)},k))}}function va(a,b,c,f,d){void 0===d&&(d=window);var e=d.Object.getOwnPropertyDescriptor(a,b);d.Object.defineProperty(a,b,f?c:{set:function(l){var k=this;setTimeout(function(){c.set.call(k,l)},0);e&&e.set&&e.set.call(this,
l)}});return function(){return va(a,b,e||{},!0)}}function za(a,b,c){try{if(!(b in a))return function(){};var f=a[b],d=c(f);"function"===typeof d&&(d.prototype=d.prototype||{},Object.defineProperties(d,{__rrweb_original__:{enumerable:!1,value:f}}));a[b]=d;return function(){a[b]=f}}catch(e){return function(){}}}function Aa(){return window.innerHeight||document.documentElement&&document.documentElement.clientHeight||document.body&&document.body.clientHeight}function Ba(){return window.innerWidth||document.documentElement&&
document.documentElement.clientWidth||document.body&&document.body.clientWidth}function X(a,b){if(!a)return!1;if(a.nodeType===a.ELEMENT_NODE){var c=!1;"string"===typeof b?c=a.classList.contains(b):a.classList.forEach(function(f){b.test(f)&&(c=!0)});return c||X(a.parentNode,b)}return X(a.parentNode,b)}function wa(a){return"__sn"in a?-2===a.__sn.id:!1}function Ca(a){var b=C.getId(a);return C.has(b)?a.parentNode&&a.parentNode.nodeType===a.DOCUMENT_NODE?!1:a.parentNode?Ca(a.parentNode):!0:!0}function Da(a){void 0===
a&&(a=window);"NodeList"in a&&!a.NodeList.prototype.forEach&&(a.NodeList.prototype.forEach=Array.prototype.forEach);"DOMTokenList"in a&&!a.DOMTokenList.prototype.forEach&&(a.DOMTokenList.prototype.forEach=Array.prototype.forEach)}function Na(a){switch(a.type){case h.EventType.DomContentLoaded:case h.EventType.Load:case h.EventType.Custom:return!1;case h.EventType.FullSnapshot:case h.EventType.Meta:return!0}switch(a.data.source){case h.IncrementalSource.MouseMove:case h.IncrementalSource.MouseInteraction:case h.IncrementalSource.TouchMove:case h.IncrementalSource.MediaInteraction:return!1}return!0}
function Oa(a){var b,c={},f=function(n,t){t={value:n,parent:t,children:[]};return c[n.node.id]=t},d=[];try{for(var e=y(a),l=e.next();!l.done;l=e.next()){var k=l.value,m=k.nextId,r=k.parentId;if(m&&m in c){var v=c[m];if(v.parent){var p=v.parent.children.indexOf(v);v.parent.children.splice(p,0,f(k,v.parent))}else p=d.indexOf(v),d.splice(p,0,f(k,null))}else if(r in c){var u=c[r];u.children.push(f(k,u))}else d.push(f(k,null))}}catch(n){var g={error:n}}finally{try{l&&!l.done&&(b=e.return)&&b.call(e)}finally{if(g)throw g.error;
}}return d}function Ea(a,b){b(a.value);for(var c=a.children.length-1;0<=c;c--)Ea(a.children[c],b)}function Fa(a,b){a.delete(b);b.childNodes.forEach(function(c){return Fa(a,c)})}function Ga(a,b){b=b.parentNode;if(!b)return!1;var c=C.getId(b);return a.some(function(f){return f.id===c})?!0:Ga(a,b)}function Ha(a,b){return(b=b.parentNode)?a.has(b)?!0:Ha(a,b):!1}function jb(a,b,c,f,d,e,l){fa.init(a,b,c,f,d,e,l);a=new MutationObserver(fa.processMutations.bind(fa));a.observe(document,{attributes:!0,attributeOldValue:!0,
characterData:!0,characterDataOldValue:!0,childList:!0,subtree:!0});return a}function kb(a,b){if(!1===b.mousemove)return function(){};b="number"===typeof b.mousemove?b.mousemove:50;var c=[],f,d=ra(function(l){var k=Date.now()-f;a(c.map(function(m){m.timeOffset-=k;return m}),l?h.IncrementalSource.TouchMove:h.IncrementalSource.MouseMove);c=[];f=null},500);b=ra(function(l){var k=l.target,m=l.changedTouches?l.changedTouches[0]:l,r=m.clientX;m=m.clientY;f||(f=Date.now());c.push({x:r,y:m,id:C.getId(k),
timeOffset:Date.now()-f});d(!!l.changedTouches)},b,{trailing:!1});var e=[ea("mousemove",b),ea("touchmove",b)];return function(){e.forEach(function(l){return l()})}}function lb(a,b,c){if(!1===c.mouseInteraction)return function(){};var f=!0===c.mouseInteraction||void 0===c.mouseInteraction?{}:c.mouseInteraction,d=[],e=function(l){return function(k){if(!X(k.target,b)){var m=C.getId(k.target);k=k.changedTouches?k.changedTouches[0]:k;a({type:h.MouseInteractions[l],id:m,x:k.clientX,y:k.clientY})}}};Object.keys(h.MouseInteractions).filter(function(l){return Number.isNaN(Number(l))&&
!l.endsWith("_Departed")&&!1!==f[l]}).forEach(function(l){var k=l.toLowerCase();l=e(l);d.push(ea(k,l))});return function(){d.forEach(function(l){return l()})}}function mb(a,b,c){c=ra(function(f){if(f.target&&!X(f.target,b)){var d=C.getId(f.target);f.target===document?(f=document.scrollingElement||document.documentElement,a({id:d,x:f.scrollLeft,y:f.scrollTop})):a({id:d,x:f.target.scrollLeft,y:f.target.scrollTop})}},c.scroll||100);return ea("scroll",c)}function nb(a){var b=ra(function(){var c=Aa(),
f=Ba();a({width:Number(f),height:Number(c)})},200);return ea("resize",b,window)}function ob(a,b,c,f,d,e){function l(v){var p=v.target;if(p&&p.tagName&&!(0>pb.indexOf(p.tagName))&&!X(p,b)&&(v=p.type,"password"!==v&&!p.classList.contains(c))){var u=p.value,g=!1;if("radio"===v||"checkbox"===v)g=p.checked;else if(f[p.tagName.toLowerCase()]||f[v])u=d?d(u):"*".repeat(u.length);k(p,{text:u,isChecked:g});u=p.name;"radio"===v&&u&&g&&document.querySelectorAll('input[type="radio"][name="'+u+'"]').forEach(function(n){n!==
p&&k(n,{text:n.value,isChecked:!g})})}}function k(v,p){var u=Pa.get(v);u&&u.text===p.text&&u.isChecked===p.isChecked||(Pa.set(v,p),v=C.getId(v),a(P(P({},p),{id:v})))}var m=("last"===e.input?["change"]:["input","change"]).map(function(v){return ea(v,l)});e=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value");var r=[[HTMLInputElement.prototype,"value"],[HTMLInputElement.prototype,"checked"],[HTMLSelectElement.prototype,"value"],[HTMLTextAreaElement.prototype,"value"],[HTMLSelectElement.prototype,
"selectedIndex"]];e&&e.set&&m.push.apply(m,x(r.map(function(v){return va(v[0],v[1],{set:function(){l({target:this})}})})));return function(){m.forEach(function(v){return v()})}}function qb(a){var b=CSSStyleSheet.prototype.insertRule;CSSStyleSheet.prototype.insertRule=function(f,d){var e=C.getId(this.ownerNode);-1!==e&&a({id:e,adds:[{rule:f,index:d}]});return b.apply(this,arguments)};var c=CSSStyleSheet.prototype.deleteRule;CSSStyleSheet.prototype.deleteRule=function(f){var d=C.getId(this.ownerNode);
-1!==d&&a({id:d,removes:[{index:f}]});return c.apply(this,arguments)};return function(){CSSStyleSheet.prototype.insertRule=b;CSSStyleSheet.prototype.deleteRule=c}}function rb(a,b){var c=function(d){return function(e){(e=e.target)&&!X(e,b)&&a({type:"play"===d?na.Play:na.Pause,id:C.getId(e)})}},f=[ea("play",c("play")),ea("pause",c("pause"))];return function(){f.forEach(function(d){return d()})}}function sb(a,b){var c,f=Object.getOwnPropertyNames(CanvasRenderingContext2D.prototype),d=[],e=function(r){try{if("function"!==
typeof CanvasRenderingContext2D.prototype[r])return"continue";var v=za(CanvasRenderingContext2D.prototype,r,function(p){return function(){for(var u=this,g=[],n=0;n<arguments.length;n++)g[n]=arguments[n];X(this.canvas,b)||setTimeout(function(){var t=x(g);"drawImage"===r&&t[0]&&t[0]instanceof HTMLCanvasElement&&(t[0]=t[0].toDataURL());a({id:C.getId(u.canvas),property:r,args:t})},0);return p.apply(this,g)}});d.push(v)}catch(p){v=va(CanvasRenderingContext2D.prototype,r,{set:function(u){a({id:C.getId(this.canvas),
property:r,args:[u],setter:!0})}}),d.push(v)}};try{for(var l=y(f),k=l.next();!k.done;k=l.next())e(k.value)}catch(r){var m={error:r}}finally{try{k&&!k.done&&(c=l.return)&&c.call(l)}finally{if(m)throw m.error;}}return function(){d.forEach(function(r){return r()})}}function tb(a){var b=[],c=new WeakMap,f=FontFace;window.FontFace=function(e,l,k){var m=new f(e,l,k);c.set(m,{family:e,buffer:"string"!==typeof l,descriptors:k,fontSource:"string"===typeof l?l:JSON.stringify(Array.from(new Uint8Array(l)))});
return m};var d=za(document.fonts,"add",function(e){return function(l){setTimeout(function(){var k=c.get(l);k&&(a(k),c.delete(l))},0);return e.apply(this,[l])}});b.push(function(){window.FonFace=f});b.push(d);return function(){b.forEach(function(e){return e()})}}function ub(a,b){var c=a.mutationCb,f=a.mousemoveCb,d=a.mouseInteractionCb,e=a.scrollCb,l=a.viewportResizeCb,k=a.inputCb,m=a.mediaInteractionCb,r=a.styleSheetRuleCb,v=a.canvasMutationCb,p=a.fontCb;a.mutationCb=function(){for(var u=[],g=0;g<
arguments.length;g++)u[g]=arguments[g];b.mutation&&b.mutation.apply(b,x(u));c.apply(void 0,x(u))};a.mousemoveCb=function(){for(var u=[],g=0;g<arguments.length;g++)u[g]=arguments[g];b.mousemove&&b.mousemove.apply(b,x(u));f.apply(void 0,x(u))};a.mouseInteractionCb=function(){for(var u=[],g=0;g<arguments.length;g++)u[g]=arguments[g];b.mouseInteraction&&b.mouseInteraction.apply(b,x(u));d.apply(void 0,x(u))};a.scrollCb=function(){for(var u=[],g=0;g<arguments.length;g++)u[g]=arguments[g];b.scroll&&b.scroll.apply(b,
x(u));e.apply(void 0,x(u))};a.viewportResizeCb=function(){for(var u=[],g=0;g<arguments.length;g++)u[g]=arguments[g];b.viewportResize&&b.viewportResize.apply(b,x(u));l.apply(void 0,x(u))};a.inputCb=function(){for(var u=[],g=0;g<arguments.length;g++)u[g]=arguments[g];b.input&&b.input.apply(b,x(u));k.apply(void 0,x(u))};a.mediaInteractionCb=function(){for(var u=[],g=0;g<arguments.length;g++)u[g]=arguments[g];b.mediaInteaction&&b.mediaInteaction.apply(b,x(u));m.apply(void 0,x(u))};a.styleSheetRuleCb=
function(){for(var u=[],g=0;g<arguments.length;g++)u[g]=arguments[g];b.styleSheetRule&&b.styleSheetRule.apply(b,x(u));r.apply(void 0,x(u))};a.canvasMutationCb=function(){for(var u=[],g=0;g<arguments.length;g++)u[g]=arguments[g];b.canvasMutation&&b.canvasMutation.apply(b,x(u));v.apply(void 0,x(u))};a.fontCb=function(){for(var u=[],g=0;g<arguments.length;g++)u[g]=arguments[g];b.font&&b.font.apply(b,x(u));p.apply(void 0,x(u))}}function vb(a,b){void 0===b&&(b={});ub(a,b);var c=jb(a.mutationCb,a.blockClass,
a.blockSelector,a.inlineStylesheet,a.maskInputOptions,a.recordCanvas,a.slimDOMOptions),f=kb(a.mousemoveCb,a.sampling),d=lb(a.mouseInteractionCb,a.blockClass,a.sampling),e=mb(a.scrollCb,a.blockClass,a.sampling),l=nb(a.viewportResizeCb),k=ob(a.inputCb,a.blockClass,a.ignoreClass,a.maskInputOptions,a.maskInputFn,a.sampling),m=rb(a.mediaInteractionCb,a.blockClass),r=qb(a.styleSheetRuleCb),v=a.recordCanvas?sb(a.canvasMutationCb,a.blockClass):function(){},p=a.collectFonts?tb(a.fontCb):function(){};return function(){c.disconnect();
f();d();e();l();k();m();r();v();p()}}function U(a){return P(P({},a),{timestamp:Date.now()})}function sa(a){function b(q){var w,I,Y,ca;void 0===q&&(q=!1);S(U({type:h.EventType.Meta,data:{href:window.location.href,width:Ba(),height:Aa()}}),q);q=fa.isFrozen();fa.freeze();var la=l;var Qa=k,ma=r,oa=G,ja=O,Ra=H;oa=void 0===oa?!1:oa;ja=void 0===ja?!1:ja;var Sa={};la=[z(document,{doc:document,map:Sa,blockClass:void 0===la?"rr-block":la,blockSelector:void 0===Qa?null:Qa,skipChild:!1,inlineStylesheet:void 0===
ma?!0:ma,maskInputOptions:!0===oa?{color:!0,date:!0,"datetime-local":!0,email:!0,month:!0,number:!0,range:!0,search:!0,tel:!0,text:!0,time:!0,url:!0,week:!0,textarea:!0,select:!0}:!1===oa?{}:oa,slimDOMOptions:!0===ja||"all"===ja?{script:!0,comment:!0,headFavicon:!0,headWhitespace:!0,headMetaDescKeywords:"all"===ja,headMetaSocial:!0,headMetaRobots:!0,headMetaHttpEquiv:!0,headMetaAuthorship:!0,headMetaVerification:!0}:!1===ja?{}:ja,recordCanvas:void 0===Ra?!1:Ra}),Sa];ma=B(la,2);la=ma[0];ma=ma[1];if(!la)return console.warn("Failed to snapshot the document");
C.map=ma;S(U({type:h.EventType.FullSnapshot,data:{node:la,initialOffset:{left:void 0!==window.pageXOffset?window.pageXOffset:(null===document||void 0===document?void 0:document.documentElement.scrollLeft)||(null===(I=null===(w=null===document||void 0===document?void 0:document.body)||void 0===w?void 0:w.parentElement)||void 0===I?void 0:I.scrollLeft)||(null===document||void 0===document?void 0:document.body.scrollLeft)||0,top:void 0!==window.pageYOffset?window.pageYOffset:(null===document||void 0===
document?void 0:document.documentElement.scrollTop)||(null===(ca=null===(Y=null===document||void 0===document?void 0:document.body)||void 0===Y?void 0:Y.parentElement)||void 0===ca?void 0:ca.scrollTop)||(null===document||void 0===document?void 0:document.body.scrollTop)||0}}}));q||(fa.emit(),fa.unfreeze())}void 0===a&&(a={});var c=a.emit,f=a.checkoutEveryNms,d=a.checkoutEveryNth,e=a.blockClass,l=void 0===e?"rr-block":e;e=a.blockSelector;var k=void 0===e?null:e;e=a.ignoreClass;var m=void 0===e?"rr-ignore":
e;e=a.inlineStylesheet;var r=void 0===e?!0:e;e=a.maskAllInputs;var v=a.maskInputOptions,p=a.slimDOMOptions,u=a.maskInputFn,g=a.hooks,n=a.packFn,t=a.sampling,A=void 0===t?{}:t;t=a.mousemoveWait;var E=a.recordCanvas,H=void 0===E?!1:E;a=a.collectFonts;var L=void 0===a?!1:a;if(!c)throw Error("emit function is required");void 0!==t&&void 0===A.mousemove&&(A.mousemove=t);var G=!0===e?{color:!0,date:!0,"datetime-local":!0,email:!0,month:!0,number:!0,range:!0,search:!0,tel:!0,text:!0,time:!0,url:!0,week:!0,
textarea:!0,select:!0}:void 0!==v?v:{},O=!0===p||"all"===p?{script:!0,comment:!0,headFavicon:!0,headWhitespace:!0,headMetaSocial:!0,headMetaRobots:!0,headMetaHttpEquiv:!0,headMetaVerification:!0,headMetaAuthorship:"all"===p,headMetaDescKeywords:"all"===p}:p?p:{};Da();var ba,ia=0;S=function(q,w){!fa.isFrozen()||q.type===h.EventType.FullSnapshot||q.type===h.EventType.IncrementalSnapshot&&q.data.source===h.IncrementalSource.Mutation||(fa.emit(),fa.unfreeze());c(n?n(q):q,w);q.type===h.EventType.FullSnapshot?
(ba=q,ia=0):q.type===h.EventType.IncrementalSnapshot&&(ia++,q=f&&q.timestamp-ba.timestamp>f,(d&&ia>=d||q)&&b(!0))};try{var Z=[];Z.push(ea("DOMContentLoaded",function(){S(U({type:h.EventType.DomContentLoaded,data:{}}))}));var ka=function(){b();Z.push(vb({mutationCb:function(q){return S(U({type:h.EventType.IncrementalSnapshot,data:P({source:h.IncrementalSource.Mutation},q)}))},mousemoveCb:function(q,w){return S(U({type:h.EventType.IncrementalSnapshot,data:{source:w,positions:q}}))},mouseInteractionCb:function(q){return S(U({type:h.EventType.IncrementalSnapshot,
data:P({source:h.IncrementalSource.MouseInteraction},q)}))},scrollCb:function(q){return S(U({type:h.EventType.IncrementalSnapshot,data:P({source:h.IncrementalSource.Scroll},q)}))},viewportResizeCb:function(q){return S(U({type:h.EventType.IncrementalSnapshot,data:P({source:h.IncrementalSource.ViewportResize},q)}))},inputCb:function(q){return S(U({type:h.EventType.IncrementalSnapshot,data:P({source:h.IncrementalSource.Input},q)}))},mediaInteractionCb:function(q){return S(U({type:h.EventType.IncrementalSnapshot,
data:P({source:h.IncrementalSource.MediaInteraction},q)}))},styleSheetRuleCb:function(q){return S(U({type:h.EventType.IncrementalSnapshot,data:P({source:h.IncrementalSource.StyleSheetRule},q)}))},canvasMutationCb:function(q){return S(U({type:h.EventType.IncrementalSnapshot,data:P({source:h.IncrementalSource.CanvasMutation},q)}))},fontCb:function(q){return S(U({type:h.EventType.IncrementalSnapshot,data:P({source:h.IncrementalSource.Font},q)}))},blockClass:l,blockSelector:k,ignoreClass:m,maskInputOptions:G,
maskInputFn:u,inlineStylesheet:r,sampling:A,recordCanvas:H,collectFonts:L,slimDOMOptions:O},g))};"interactive"===document.readyState||"complete"===document.readyState?ka():Z.push(ea("load",function(){S(U({type:h.EventType.Load,data:{}}));ka()},window));return function(){Z.forEach(function(q){return q()})}}catch(q){console.warn(q)}}function Ta(a){a=a||Object.create(null);return{on:function(b,c){(a[b]||(a[b]=[])).push(c)},off:function(b,c){a[b]&&a[b].splice(a[b].indexOf(c)>>>0,1)},emit:function(b,c){(a[b]||
[]).slice().map(function(f){f(c)});(a["*"]||[]).slice().map(function(f){f(b,c)})}}}function wb(a,b){function c(g,n){this.scrollLeft=g;this.scrollTop=n}function f(g){if(null===g||"object"!==typeof g||void 0===g.behavior||"auto"===g.behavior||"instant"===g.behavior)return!0;if("object"===typeof g&&"smooth"===g.behavior)return!1;throw new TypeError("behavior member of ScrollOptions "+g.behavior+" is not a valid value for enumeration ScrollBehavior.");}function d(g,n){if("Y"===n)return g.clientHeight+
u<g.scrollHeight;if("X"===n)return g.clientWidth+u<g.scrollWidth}function e(g,n){g=a.getComputedStyle(g,null)["overflow"+n];return"auto"===g||"scroll"===g}function l(g){var n=d(g,"Y")&&e(g,"Y");g=d(g,"X")&&e(g,"X");return n||g}function k(g){var n=(p()-g.startTime)/468;var t=.5*(1-Math.cos(Math.PI*(1<n?1:n)));n=g.startX+(g.x-g.startX)*t;t=g.startY+(g.y-g.startY)*t;g.method.call(g.scrollable,n,t);n===g.x&&t===g.y||a.requestAnimationFrame(k.bind(a,g))}function m(g,n,t){var A=p();if(g===b.body){var E=
a;var H=a.scrollX||a.pageXOffset;g=a.scrollY||a.pageYOffset;var L=v.scroll}else E=g,H=g.scrollLeft,g=g.scrollTop,L=c;k({scrollable:E,method:L,startTime:A,startX:H,startY:g,x:n,y:t})}void 0===a&&(a=window);void 0===b&&(b=document);if(!("scrollBehavior"in b.documentElement.style&&!0!==a.__forceSmoothScrollPolyfill__)){var r=a.HTMLElement||a.Element,v={scroll:a.scroll||a.scrollTo,scrollBy:a.scrollBy,elementScroll:r.prototype.scroll||c,scrollIntoView:r.prototype.scrollIntoView},p=a.performance&&a.performance.now?
a.performance.now.bind(a.performance):Date.now,u=/MSIE |Trident\/|Edge\//.test(a.navigator.userAgent)?1:0;a.scroll=a.scrollTo=function(g,n){void 0!==g&&(!0===f(g)?v.scroll.call(a,void 0!==g.left?g.left:"object"!==typeof g?g:a.scrollX||a.pageXOffset,void 0!==g.top?g.top:void 0!==n?n:a.scrollY||a.pageYOffset):m.call(a,b.body,void 0!==g.left?~~g.left:a.scrollX||a.pageXOffset,void 0!==g.top?~~g.top:a.scrollY||a.pageYOffset))};a.scrollBy=function(g,n){void 0!==g&&(f(g)?v.scrollBy.call(a,void 0!==g.left?
g.left:"object"!==typeof g?g:0,void 0!==g.top?g.top:void 0!==n?n:0):m.call(a,b.body,~~g.left+(a.scrollX||a.pageXOffset),~~g.top+(a.scrollY||a.pageYOffset)))};r.prototype.scroll=r.prototype.scrollTo=function(g,n){if(void 0!==g)if(!0===f(g)){if("number"===typeof g&&void 0===n)throw new SyntaxError("Value could not be converted");v.elementScroll.call(this,void 0!==g.left?~~g.left:"object"!==typeof g?~~g:this.scrollLeft,void 0!==g.top?~~g.top:void 0!==n?~~n:this.scrollTop)}else n=g.left,g=g.top,m.call(this,
this,"undefined"===typeof n?this.scrollLeft:~~n,"undefined"===typeof g?this.scrollTop:~~g)};r.prototype.scrollBy=function(g,n){void 0!==g&&(!0===f(g)?v.elementScroll.call(this,void 0!==g.left?~~g.left+this.scrollLeft:~~g+this.scrollLeft,void 0!==g.top?~~g.top+this.scrollTop:~~n+this.scrollTop):this.scroll({left:~~g.left+this.scrollLeft,top:~~g.top+this.scrollTop,behavior:g.behavior}))};r.prototype.scrollIntoView=function(g){if(!0===f(g))v.scrollIntoView.call(this,void 0===g?!0:g);else{for(g=this;g!==
b.body&&!1===l(g);)g=g.parentNode||g.host;var n=g.getBoundingClientRect(),t=this.getBoundingClientRect();g!==b.body?(m.call(this,g,g.scrollLeft+t.left-n.left,g.scrollTop+t.top-n.top),"fixed"!==a.getComputedStyle(g).position&&a.scrollBy({left:n.left,top:n.top,behavior:"smooth"})):a.scrollBy({left:t.left,top:t.top,behavior:"smooth"})}}}}function Ua(a,b){if(a.type===h.EventType.IncrementalSnapshot&&a.data.source===h.IncrementalSource.MouseMove){var c=a.timestamp+a.data.positions[0].timeOffset;a.delay=
c-b;return c-b}a.delay=a.timestamp-b;return a.delay}function Va(a){return void 0===a?[]:[].concat(a)}function pa(a){return{type:"xstate.assign",assignment:a}}function Wa(a,b){return"string"==typeof(a="string"==typeof a&&b&&b[a]?b[a]:a)?{type:a}:"function"==typeof a?{type:a.name,exec:a}:a}function xa(a){return function(b){return a===b}}function Xa(a,b){return{value:a,context:b,actions:[],changed:!1,matches:xa(a)}}function Ya(a,b){void 0===b&&(b={});var c={config:a,_options:b,initialState:{value:a.initial,
actions:Va(a.states[a.initial].entry).map(function(f){return Wa(f,b.actions)}),context:a.context,matches:xa(a.initial)},transition:function(f,d){var e;f="string"==typeof f?{value:f,context:a.context}:f;var l=f.value,k=f.context,m="string"==typeof d?{type:d}:d,r=a.states[l];if(r.on){d=Va(r.on[m.type]);f=function(n){if(void 0===n)return{value:Xa(l,k)};var t="string"==typeof n?{target:n}:n;n=t.target;n=void 0===n?l:n;var A=t.actions;A=void 0===A?[]:A;t=t.cond;var E=k;if((void 0===t?function(){return!0}:
t)(k,m)){var H=!1;t=[].concat(r.exit,A,a.states[n].entry).filter(function(L){return L}).map(function(L){return Wa(L,c._options.actions)}).filter(function(L){if("xstate.assign"===L.type){H=!0;var G=Object.assign({},E);return"function"==typeof L.assignment?G=L.assignment(E,m):Object.keys(L.assignment).forEach(function(O){G[O]="function"==typeof L.assignment[O]?L.assignment[O](E,m):L.assignment[O]}),E=G,!1}return!0});return{value:{value:n,context:E,actions:t,changed:n!==l||0<t.length||H,matches:xa(n)}}}};
try{for(var v=function(n){var t="function"==typeof Symbol&&n[Symbol.iterator],A=0;return t?t.call(n):{next:function(){return n&&A>=n.length&&(n=void 0),{value:n&&n[A++],done:!n}}}}(d),p=v.next();!p.done;p=v.next()){var u=f(p.value);if("object"==typeof u)return u.value}}catch(n){var g={error:n}}finally{try{p&&!p.done&&(e=v.return)&&e.call(v)}finally{if(g)throw g.error;}}}return Xa(l,k)}};return c}function Za(a){var b=a.initialState,c=qa.NotStarted,f=new Set,d={_machine:a,send:function(e){c===qa.Running&&
(b=a.transition(b,e),$a(b,"string"==typeof e?{type:e}:e),f.forEach(function(l){return l(b)}))},subscribe:function(e){return f.add(e),e(b),{unsubscribe:function(){return f.delete(e)}}},start:function(e){e&&(e="object"==typeof e?e:{context:a.config.context,value:e},b={value:e.value,actions:[],context:e.context,matches:xa(e.value)});return c=qa.Running,$a(b,xb),d},stop:function(){return c=qa.Stopped,f.clear(),d},get state(){return b},get status(){return c}};return d}function yb(a,b){for(var c=a.length-
1;0<=c;c--){var f=a[c];if(f.type===h.EventType.Meta&&f.timestamp<=b)return a.slice(c)}return a}function zb(a,b){var c=b.getCastFn,f=b.emitter;a=Ya({id:"player",context:a,initial:"paused",states:{playing:{on:{PAUSE:{target:"paused",actions:["pause"]},CAST_EVENT:{target:"playing",actions:"castEvent"},END:{target:"paused",actions:["resetLastPlayedEvent","pause"]},ADD_EVENT:{target:"playing",actions:["addEvent"]}}},paused:{on:{PLAY:{target:"playing",actions:["recordTimeOffset","play"]},CAST_EVENT:{target:"paused",
actions:"castEvent"},TO_LIVE:{target:"live",actions:["startLive"]},ADD_EVENT:{target:"paused",actions:["addEvent"]}}},live:{on:{ADD_EVENT:{target:"live",actions:["addEvent"]},CAST_EVENT:{target:"live",actions:["castEvent"]}}}}},{actions:{castEvent:pa({lastPlayedEvent:function(d,e){return"CAST_EVENT"===e.type?e.payload.event:d.lastPlayedEvent}}),recordTimeOffset:pa(function(d,e){var l=d.timeOffset;"payload"in e&&"timeOffset"in e.payload&&(l=e.payload.timeOffset);return P(P({},d),{timeOffset:l,baselineTime:d.events[0].timestamp+
l})}),play:function(d){var e,l,k,m=d.timer,r=d.events,v=d.baselineTime,p=d.lastPlayedEvent;m.clear();try{for(var u=y(r),g=u.next();!g.done;g=u.next()){var n=g.value;Ua(n,v)}}catch(G){var t={error:G}}finally{try{g&&!g.done&&(e=u.return)&&e.call(u)}finally{if(t)throw t.error;}}d=yb(r,v);var A=[];t=function(G){var O=null===p||void 0===p?void 0:p.timestamp;(null===p||void 0===p?void 0:p.type)===h.EventType.IncrementalSnapshot&&p.data.source===h.IncrementalSource.MouseMove&&(O=p.timestamp+(null===(k=p.data.positions[0])||
void 0===k?void 0:k.timeOffset));if(O&&O<v&&(G.timestamp<=O||G===p)||(O=G.timestamp<v)&&!Na(G))return"continue";var ba=c(G,O);O?ba():A.push({doAction:function(){ba();f.emit(h.ReplayerEvents.EventCast,G)},delay:G.delay})};try{for(var E=y(d),H=E.next();!H.done;H=E.next())n=H.value,t(n)}catch(G){var L={error:G}}finally{try{H&&!H.done&&(l=E.return)&&l.call(E)}finally{if(L)throw L.error;}}f.emit(h.ReplayerEvents.Flush);m.addActions(A);m.start()},pause:function(d){d.timer.clear()},resetLastPlayedEvent:pa(function(d){return P(P({},
d),{lastPlayedEvent:null})}),startLive:pa({baselineTime:function(d,e){d.timer.toggleLiveMode(!0);d.timer.start();return"TO_LIVE"===e.type&&e.payload.baselineTime?e.payload.baselineTime:Date.now()}}),addEvent:pa(function(d,e){var l=d.baselineTime,k=d.timer,m=d.events;if("ADD_EVENT"===e.type){var r=e.payload.event;Ua(r,l);m.push(r);e=r.timestamp<l;var v=c(r,e);e?v():(k.addAction({doAction:function(){v();f.emit(h.ReplayerEvents.EventCast,r)},delay:r.delay}),k.isActive()||k.start())}return P(P({},d),
{events:m})})}});return Za(a)}function Ab(a){a=Ya({id:"speed",context:a,initial:"normal",states:{normal:{on:{FAST_FORWARD:{target:"skipping",actions:["recordSpeed","setSpeed"]},SET_SPEED:{target:"normal",actions:["setSpeed"]}}},skipping:{on:{BACK_TO_NORMAL:{target:"normal",actions:["restoreSpeed"]},SET_SPEED:{target:"normal",actions:["setSpeed"]}}}}},{actions:{setSpeed:function(b,c){"payload"in c&&b.timer.setSpeed(c.payload.speed)},recordSpeed:pa({normalSpeed:function(b){return b.timer.speed}}),restoreSpeed:function(b){b.timer.setSpeed(b.normalSpeed)}}});
return Za(a)}var P=function(){P=Object.assign||function(a){for(var b,c=1,f=arguments.length;c<f;c++){b=arguments[c];for(var d in b)Object.prototype.hasOwnProperty.call(b,d)&&(a[d]=b[d])}return a};return P.apply(this,arguments)},N;(function(a){a[a.Document=0]="Document";a[a.DocumentType=1]="DocumentType";a[a.Element=2]="Element";a[a.Text=3]="Text";a[a.CDATA=4]="CDATA";a[a.Comment=5]="Comment"})(N||(N={}));var fb=1,bb=/[^a-z1-6-_]/,cb=/url\((?:(')([^']*)'|(")([^"]*)"|([^)]*))\)/gm,db=/^(?!www\.|(?:http|ftp)s?:\/\/|[A-Za-z]:\\|\/\/).*/,
eb=/^(data:)([^,]*),(.*)/i,Ka=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//g,La={script:"noscript",altglyph:"altGlyph",altglyphdef:"altGlyphDef",altglyphitem:"altGlyphItem",animatecolor:"animateColor",animatemotion:"animateMotion",animatetransform:"animateTransform",clippath:"clipPath",feblend:"feBlend",fecolormatrix:"feColorMatrix",fecomponenttransfer:"feComponentTransfer",fecomposite:"feComposite",feconvolvematrix:"feConvolveMatrix",fediffuselighting:"feDiffuseLighting",fedisplacementmap:"feDisplacementMap",
fedistantlight:"feDistantLight",fedropshadow:"feDropShadow",feflood:"feFlood",fefunca:"feFuncA",fefuncb:"feFuncB",fefuncg:"feFuncG",fefuncr:"feFuncR",fegaussianblur:"feGaussianBlur",feimage:"feImage",femerge:"feMerge",femergenode:"feMergeNode",femorphology:"feMorphology",feoffset:"feOffset",fepointlight:"fePointLight",fespecularlighting:"feSpecularLighting",fespotlight:"feSpotLight",fetile:"feTile",feturbulence:"feTurbulence",foreignobject:"foreignObject",glyphref:"glyphRef",lineargradient:"linearGradient",
radialgradient:"radialGradient"},Ma=/([^\\]):hover/g;(function(a){a[a.DomContentLoaded=0]="DomContentLoaded";a[a.Load=1]="Load";a[a.FullSnapshot=2]="FullSnapshot";a[a.IncrementalSnapshot=3]="IncrementalSnapshot";a[a.Meta=4]="Meta";a[a.Custom=5]="Custom"})(h.EventType||(h.EventType={}));(function(a){a[a.Mutation=0]="Mutation";a[a.MouseMove=1]="MouseMove";a[a.MouseInteraction=2]="MouseInteraction";a[a.Scroll=3]="Scroll";a[a.ViewportResize=4]="ViewportResize";a[a.Input=5]="Input";a[a.TouchMove=6]="TouchMove";
a[a.MediaInteraction=7]="MediaInteraction";a[a.StyleSheetRule=8]="StyleSheetRule";a[a.CanvasMutation=9]="CanvasMutation";a[a.Font=10]="Font"})(h.IncrementalSource||(h.IncrementalSource={}));(function(a){a[a.MouseUp=0]="MouseUp";a[a.MouseDown=1]="MouseDown";a[a.Click=2]="Click";a[a.ContextMenu=3]="ContextMenu";a[a.DblClick=4]="DblClick";a[a.Focus=5]="Focus";a[a.Blur=6]="Blur";a[a.TouchStart=7]="TouchStart";a[a.TouchMove_Departed=8]="TouchMove_Departed";a[a.TouchEnd=9]="TouchEnd"})(h.MouseInteractions||
(h.MouseInteractions={}));var na;(function(a){a[a.Play=0]="Play";a[a.Pause=1]="Pause"})(na||(na={}));(function(a){a.Start="start";a.Pause="pause";a.Resume="resume";a.Resize="resize";a.Finish="finish";a.FullsnapshotRebuilded="fullsnapshot-rebuilded";a.LoadStylesheetStart="load-stylesheet-start";a.LoadStylesheetEnd="load-stylesheet-end";a.SkipStart="skip-start";a.SkipEnd="skip-end";a.MouseInteraction="mouse-interaction";a.EventCast="event-cast";a.CustomEvent="custom-event";a.Flush="flush";a.StateChange=
"state-change"})(h.ReplayerEvents||(h.ReplayerEvents={}));var C={map:{},getId:function(a){return a.__sn?a.__sn.id:-1},getNode:function(a){return C.map[a]||null},removeNodeFromMap:function(a){delete C.map[a.__sn&&a.__sn.id];a.childNodes&&a.childNodes.forEach(function(b){return C.removeNodeFromMap(b)})},has:function(a){return C.map.hasOwnProperty(a)}},ab=function(){function a(){this.reset()}a.prototype.add=function(b){var c=this.indexes.get(b.parentId);b={id:b.node.id,mutation:b,children:[],texts:[],
attributes:[]};c?(b.parent=c,c.children[b.id]=b):this.tree[b.id]=b;this.indexes.set(b.id,b)};a.prototype.remove=function(b){var c=this,f=this.indexes.get(b.parentId),d=this.indexes.get(b.id),e=function(k){c.removeIdSet.add(k);k=C.getNode(k);null===k||void 0===k?void 0:k.childNodes.forEach(function(m){"__sn"in m&&e(m.__sn.id)})},l=function(k){c.removeIdSet.add(k.id);Object.values(k.children).forEach(function(r){return l(r)});if(k=c.indexes.get(k.id)){var m=k.parent;m&&(delete k.parent,delete m.children[k.id],
c.indexes.delete(b.id))}};d?(f?(delete d.parent,delete f.children[d.id],this.indexes.delete(b.id)):(delete this.tree[d.id],this.indexes.delete(d.id)),l(d)):(this.removeNodeMutations.push(b),e(b.id))};a.prototype.text=function(b){var c=this.indexes.get(b.id);c?c.texts.push(b):this.textMutations.push(b)};a.prototype.attribute=function(b){var c=this.indexes.get(b.id);c?c.attributes.push(b):this.attributeMutations.push(b)};a.prototype.scroll=function(b){this.scrollMap.set(b.id,b)};a.prototype.input=function(b){this.inputMap.set(b.id,
b)};a.prototype.flush=function(){var b,c,f=this,d={source:h.IncrementalSource.Mutation,removes:this.removeNodeMutations,texts:this.textMutations,attributes:this.attributeMutations,adds:[]},e=function(g,n){n&&f.removeIdSet.add(g.id);d.texts=d.texts.concat(n?[]:g.texts).filter(function(t){return!f.removeIdSet.has(t.id)});d.attributes=d.attributes.concat(n?[]:g.attributes).filter(function(t){return!f.removeIdSet.has(t.id)});f.removeIdSet.has(g.id)||f.removeIdSet.has(g.mutation.parentId)||n?Object.values(g.children).forEach(function(t){return e(t,
!0)}):(d.adds.push(g.mutation),g.children&&Object.values(g.children).forEach(function(t){return e(t,!1)}))};Object.values(this.tree).forEach(function(g){return e(g,!1)});try{for(var l=y(this.scrollMap.keys()),k=l.next();!k.done;k=l.next()){var m=k.value;this.removeIdSet.has(m)&&this.scrollMap.delete(m)}}catch(g){var r={error:g}}finally{try{k&&!k.done&&(b=l.return)&&b.call(l)}finally{if(r)throw r.error;}}try{for(var v=y(this.inputMap.keys()),p=v.next();!p.done;p=v.next())m=p.value,this.removeIdSet.has(m)&&
this.inputMap.delete(m)}catch(g){var u={error:g}}finally{try{p&&!p.done&&(c=v.return)&&c.call(v)}finally{if(u)throw u.error;}}r=new Map(this.scrollMap);b=new Map(this.inputMap);this.reset();return{mutationData:d,scrollMap:r,inputMap:b}};a.prototype.reset=function(){this.tree=[];this.indexes=new Map;this.removeNodeMutations=[];this.textMutations=[];this.attributeMutations=[];this.removeIdSet=new Set;this.scrollMap=new Map;this.inputMap=new Map};return a}(),Bb=Object.freeze({__proto__:null,on:ea,mirror:C,
throttle:ra,hookSetter:va,patch:za,getWindowHeight:Aa,getWindowWidth:Ba,isBlocked:X,isIgnored:wa,isAncestorRemoved:Ca,isTouchEvent:function(a){return!!a.changedTouches},polyfill:Da,needCastInSyncMode:Na,TreeIndex:ab,queueToResolveTrees:Oa,iterateResolveTree:Ea}),Cb=function(){function a(){this.length=0;this.head=null}a.prototype.get=function(b){if(b>=this.length)throw Error("Position outside of list range");for(var c=this.head,f=0;f<b;f++)c=(null===c||void 0===c?void 0:c.next)||null;return c};a.prototype.addNode=
function(b){var c={value:b,previous:null,next:null};b.__ln=c;if(b.previousSibling&&"__ln"in b.previousSibling){var f=b.previousSibling.__ln.next;c.next=f;c.previous=b.previousSibling.__ln;b.previousSibling.__ln.next=c;f&&(f.previous=c)}else b.nextSibling&&"__ln"in b.nextSibling?(f=b.nextSibling.__ln.previous,c.previous=f,c.next=b.nextSibling.__ln,b.nextSibling.__ln.previous=c,f&&(f.next=c)):(this.head&&(this.head.previous=c),c.next=this.head,this.head=c);this.length++};a.prototype.removeNode=function(b){var c=
b.__ln;if(this.head){if(c.previous){if(c.previous.next=c.next)c.next.previous=c.previous}else if(this.head=c.next)this.head.previous=null;b.__ln&&delete b.__ln;this.length--}};return a}(),fa=new (function(){function a(){var b=this;this.frozen=!1;this.texts=[];this.attributes=[];this.removes=[];this.mapRemoves=[];this.movedMap={};this.addedSet=new Set;this.movedSet=new Set;this.droppedSet=new Set;this.processMutations=function(c){c.forEach(b.processMutation);b.frozen||b.emit()};this.emit=function(){for(var c,
f,d,e,l=[],k=new Cb,m=function(t){for(var A=t,E=-2;-2===E;)E=(A=A&&A.nextSibling)&&C.getId(A);-1===E&&X(t.nextSibling,b.blockClass)&&(E=null);return E},r=function(t){if(t.parentNode){var A=C.getId(t.parentNode),E=m(t);if(-1===A||-1===E)return k.addNode(t);(t=z(t,{doc:document,map:C.map,blockClass:b.blockClass,blockSelector:b.blockSelector,skipChild:!0,inlineStylesheet:b.inlineStylesheet,maskInputOptions:b.maskInputOptions,slimDOMOptions:b.slimDOMOptions,recordCanvas:b.recordCanvas}))&&l.push({parentId:A,
nextId:E,node:t})}};b.mapRemoves.length;)C.removeNodeFromMap(b.mapRemoves.shift());try{for(var v=y(b.movedSet),p=v.next();!p.done;p=v.next()){var u=p.value;Ga(b.removes,u)&&!b.movedSet.has(u.parentNode)||r(u)}}catch(t){c={error:t}}finally{try{p&&!p.done&&(f=v.return)&&f.call(v)}finally{if(c)throw c.error;}}try{for(var g=y(b.addedSet),n=g.next();!n.done;n=g.next())u=n.value,Ha(b.droppedSet,u)||Ga(b.removes,u)?Ha(b.movedSet,u)?r(u):b.droppedSet.add(u):r(u)}catch(t){d={error:t}}finally{try{n&&!n.done&&
(e=g.return)&&e.call(g)}finally{if(d)throw d.error;}}for(e=null;k.length;){c=null;e&&(f=C.getId(e.value.parentNode),d=m(e.value),-1!==f&&-1!==d&&(c=e));if(!c)for(e=k.length-1;0<=e;e--)if(v=k.get(e),f=C.getId(v.value.parentNode),d=m(v.value),-1!==f&&-1!==d){c=v;break}if(!c)break;e=c.previous;k.removeNode(c.value);r(c.value)}r={texts:b.texts.map(function(t){return{id:C.getId(t.node),value:t.value}}).filter(function(t){return C.has(t.id)}),attributes:b.attributes.map(function(t){return{id:C.getId(t.node),
attributes:t.attributes}}).filter(function(t){return C.has(t.id)}),removes:b.removes,adds:l};if(r.texts.length||r.attributes.length||r.removes.length||r.adds.length)b.texts=[],b.attributes=[],b.removes=[],b.addedSet=new Set,b.movedSet=new Set,b.droppedSet=new Set,b.movedMap={},b.emissionCallback(r)};this.processMutation=function(c){if(!wa(c.target))switch(c.type){case "characterData":var f=c.target.textContent;X(c.target,b.blockClass)||f===c.oldValue||b.texts.push({value:f,node:c.target});break;case "attributes":f=
c.target.getAttribute(c.attributeName);if(X(c.target,b.blockClass)||f===c.oldValue)break;var d=b.attributes.find(function(e){return e.node===c.target});d||(d={node:c.target,attributes:{}},b.attributes.push(d));d.attributes[c.attributeName]=ha(document,c.attributeName,f);break;case "childList":c.addedNodes.forEach(function(e){return b.genAdds(e,c.target)}),c.removedNodes.forEach(function(e){var l=C.getId(e),k=C.getId(c.target);X(e,b.blockClass)||X(c.target,b.blockClass)||wa(e)||(b.addedSet.has(e)?
(Fa(b.addedSet,e),b.droppedSet.add(e)):b.addedSet.has(c.target)&&-1===l||Ca(c.target)||(b.movedSet.has(e)&&b.movedMap[l+"@"+k]?Fa(b.movedSet,e):b.removes.push({parentId:k,id:l})),b.mapRemoves.push(e))})}};this.genAdds=function(c,f){if(!X(c,b.blockClass)){if("__sn"in c){if(wa(c))return;b.movedSet.add(c);var d=null;f&&"__sn"in f&&(d=f.__sn.id);d&&(b.movedMap[c.__sn.id+"@"+d]=!0)}else b.addedSet.add(c),b.droppedSet.delete(c);c.childNodes.forEach(function(e){return b.genAdds(e)})}}}a.prototype.init=function(b,
c,f,d,e,l,k){this.blockClass=c;this.blockSelector=f;this.inlineStylesheet=d;this.maskInputOptions=e;this.recordCanvas=l;this.slimDOMOptions=k;this.emissionCallback=b};a.prototype.freeze=function(){this.frozen=!0};a.prototype.unfreeze=function(){this.frozen=!1};a.prototype.isFrozen=function(){return this.frozen};return a}()),pb=["INPUT","TEXTAREA","SELECT"],Pa=new WeakMap,S;sa.addCustomEvent=function(a,b){if(!S)throw Error("please add custom event after start recording");S(U({type:h.EventType.Custom,
data:{tag:a,payload:b}}))};sa.freezePage=function(){fa.freeze()};var Ia=Object.freeze({__proto__:null,"default":Ta}),Db=function(){function a(b,c){void 0===b&&(b=[]);this.timeOffset=0;this.raf=null;this.actions=b;this.speed=c}a.prototype.addAction=function(b){var c=this.findActionIndex(b);this.actions.splice(c,0,b)};a.prototype.addActions=function(b){var c;(c=this.actions).push.apply(c,x(b))};a.prototype.start=function(){function b(e){d.timeOffset+=(e-c)*d.speed;for(c=e;f.length;)if(e=f[0],d.timeOffset>=
e.delay)f.shift(),e.doAction();else break;if(0<f.length||d.liveMode)d.raf=requestAnimationFrame(b)}this.actions.sort(function(e,l){return e.delay-l.delay});this.timeOffset=0;var c=performance.now(),f=this.actions,d=this;this.raf=requestAnimationFrame(b)};a.prototype.clear=function(){this.raf&&(cancelAnimationFrame(this.raf),this.raf=null);this.actions.length=0};a.prototype.setSpeed=function(b){this.speed=b};a.prototype.toggleLiveMode=function(b){this.liveMode=b};a.prototype.isActive=function(){return null!==
this.raf};a.prototype.findActionIndex=function(b){for(var c=0,f=this.actions.length-1;c<=f;){var d=Math.floor((c+f)/2);if(this.actions[d].delay<b.delay)c=d+1;else if(this.actions[d].delay>b.delay)f=d-1;else return d}return c};return a}(),qa;!function(a){a[a.NotStarted=0]="NotStarted";a[a.Running=1]="Running";a[a.Stopped=2]="Stopped"}(qa||(qa={}));var xb={type:"xstate.init"},$a=function(a,b){return a.actions.forEach(function(c){return(c=c.exec)&&c(a.context,b)})},Eb=Ta||Ia,Ja={duration:500,lineCap:"round",
lineWidth:3,strokeStyle:"red"};Ia=function(){function a(b,c){var f=this;this.mouseTail=null;this.tailPositions=[];this.emitter=Eb();this.legacy_missingNodeRetryMap={};this.imageMap=new Map;if((null===c||void 0===c||!c.liveMode)&&2>b.length)throw Error("Replayer need at least 2 events.");var d={speed:1,root:document.body,loadTimeout:0,skipInactive:!1,showWarning:!0,showDebug:!1,blockClass:"rr-block",liveMode:!1,insertStyleRules:[],triggerFocus:!0,UNSAFE_replayCanvas:!1,pauseAnimation:!0,mouseTail:Ja};
this.config=Object.assign({},d,c);this.handleResize=this.handleResize.bind(this);this.getCastFn=this.getCastFn.bind(this);this.emitter.on(h.ReplayerEvents.Resize,this.handleResize);this.setupDom();this.treeIndex=new ab;this.fragmentParentMap=new Map;this.elementStateMap=new Map;this.emitter.on(h.ReplayerEvents.Flush,function(){var m,r,v,p=f.treeIndex.flush(),u=p.scrollMap;p=p.inputMap;try{for(var g=y(f.fragmentParentMap.entries()),n=g.next();!n.done;n=g.next()){var t=B(n.value,2),A=t[0],E=t[1];C.map[E.__sn.id]=
E;E.__sn.type===N.Element&&"textarea"===E.__sn.tagName&&A.textContent&&(E.value=A.textContent);E.appendChild(A);f.restoreState(E)}}catch(q){var H={error:q}}finally{try{n&&!n.done&&(m=g.return)&&m.call(g)}finally{if(H)throw H.error;}}f.fragmentParentMap.clear();f.elementStateMap.clear();try{for(var L=y(u.values()),G=L.next();!G.done;G=L.next()){var O=G.value;f.applyScroll(O)}}catch(q){var ba={error:q}}finally{try{G&&!G.done&&(r=L.return)&&r.call(L)}finally{if(ba)throw ba.error;}}try{for(var ia=y(p.values()),
Z=ia.next();!Z.done;Z=ia.next())O=Z.value,f.applyInput(O)}catch(q){var ka={error:q}}finally{try{Z&&!Z.done&&(v=ia.return)&&v.call(ia)}finally{if(ka)throw ka.error;}}});d=new Db([],(null===c||void 0===c?void 0:c.speed)||d.speed);this.service=zb({events:b.map(function(m){return c&&c.unpackFn?c.unpackFn(m):m}),timer:d,timeOffset:0,baselineTime:0,lastPlayedEvent:null},{getCastFn:this.getCastFn,emitter:this.emitter});this.service.start();this.service.subscribe(function(m){f.emitter.emit(h.ReplayerEvents.StateChange,
{player:m})});this.speedService=Ab({normalSpeed:-1,timer:d});this.speedService.start();this.speedService.subscribe(function(m){f.emitter.emit(h.ReplayerEvents.StateChange,{speed:m})});b=this.service.state.context.events.find(function(m){return m.type===h.EventType.Meta});var e=this.service.state.context.events.find(function(m){return m.type===h.EventType.FullSnapshot});if(b){b=b.data;var l=b.width,k=b.height;setTimeout(function(){f.emitter.emit(h.ReplayerEvents.Resize,{width:l,height:k})},0)}e&&setTimeout(function(){f.rebuildFullSnapshot(e)},
1)}Object.defineProperty(a.prototype,"timer",{get:function(){return this.service.state.context.timer},enumerable:!1,configurable:!0});a.prototype.on=function(b,c){this.emitter.on(b,c);return this};a.prototype.setConfig=function(b){var c=this;Object.keys(b).forEach(function(f){c.config[f]=b[f]});this.config.skipInactive||this.backToNormal();"undefined"!==typeof b.speed&&this.speedService.send({type:"SET_SPEED",payload:{speed:b.speed}});"undefined"!==typeof b.mouseTail&&(!1===b.mouseTail?this.mouseTail&&
(this.mouseTail.style.display="none"):(this.mouseTail||(this.mouseTail=document.createElement("canvas"),this.mouseTail.width=Number.parseFloat(this.iframe.width),this.mouseTail.height=Number.parseFloat(this.iframe.height),this.mouseTail.classList.add("replayer-mouse-tail"),this.wrapper.insertBefore(this.mouseTail,this.iframe)),this.mouseTail.style.display="inherit"))};a.prototype.getMetaData=function(){var b=this.service.state.context.events[0],c=this.service.state.context.events[this.service.state.context.events.length-
1];return{startTime:b.timestamp,endTime:c.timestamp,totalTime:c.timestamp-b.timestamp}};a.prototype.getCurrentTime=function(){return this.timer.timeOffset+this.getTimeOffset()};a.prototype.getTimeOffset=function(){var b=this.service.state.context;return b.baselineTime-b.events[0].timestamp};a.prototype.play=function(b){var c;void 0===b&&(b=0);this.service.state.matches("paused")||this.service.send({type:"PAUSE"});this.service.send({type:"PLAY",payload:{timeOffset:b}});null===(c=this.iframe.contentDocument)||
void 0===c?void 0:c.getElementsByTagName("html")[0].classList.remove("rrweb-paused");this.emitter.emit(h.ReplayerEvents.Start)};a.prototype.pause=function(b){var c;void 0===b&&this.service.state.matches("playing")&&this.service.send({type:"PAUSE"});"number"===typeof b&&(this.play(b),this.service.send({type:"PAUSE"}));null===(c=this.iframe.contentDocument)||void 0===c?void 0:c.getElementsByTagName("html")[0].classList.add("rrweb-paused");this.emitter.emit(h.ReplayerEvents.Pause)};a.prototype.resume=
function(b){void 0===b&&(b=0);console.warn("The 'resume' will be departed in 1.0. Please use 'play' method which has the same interface.");this.play(b);this.emitter.emit(h.ReplayerEvents.Resume)};a.prototype.startLive=function(b){this.service.send({type:"TO_LIVE",payload:{baselineTime:b}})};a.prototype.addEvent=function(b){var c=this,f=this.config.unpackFn?this.config.unpackFn(b):b;Promise.resolve().then(function(){return c.service.send({type:"ADD_EVENT",payload:{event:f}})})};a.prototype.enableInteract=
function(){this.iframe.setAttribute("scrolling","auto");this.iframe.style.pointerEvents="auto"};a.prototype.disableInteract=function(){this.iframe.setAttribute("scrolling","no");this.iframe.style.pointerEvents="none"};a.prototype.setupDom=function(){this.wrapper=document.createElement("div");this.wrapper.classList.add("replayer-wrapper");this.config.root.appendChild(this.wrapper);this.mouse=document.createElement("div");this.mouse.classList.add("replayer-mouse");this.wrapper.appendChild(this.mouse);
!1!==this.config.mouseTail&&(this.mouseTail=document.createElement("canvas"),this.mouseTail.classList.add("replayer-mouse-tail"),this.mouseTail.style.display="inherit",this.wrapper.appendChild(this.mouseTail));this.iframe=document.createElement("iframe");var b=["allow-same-origin"];this.config.UNSAFE_replayCanvas&&b.push("allow-scripts");this.iframe.style.display="none";this.iframe.setAttribute("sandbox",b.join(" "));this.disableInteract();this.wrapper.appendChild(this.iframe);this.iframe.contentWindow&&
this.iframe.contentDocument&&(wb(this.iframe.contentWindow,this.iframe.contentDocument),Da(this.iframe.contentWindow))};a.prototype.handleResize=function(b){var c;this.iframe.style.display="inherit";try{for(var f=y([this.mouseTail,this.iframe]),d=f.next();!d.done;d=f.next()){var e=d.value;e&&(e.setAttribute("width",String(b.width)),e.setAttribute("height",String(b.height)))}}catch(k){var l={error:k}}finally{try{d&&!d.done&&(c=f.return)&&c.call(f)}finally{if(l)throw l.error;}}};a.prototype.getCastFn=
function(b,c){var f=this;void 0===c&&(c=!1);switch(b.type){case h.EventType.Custom:var d=function(){f.emitter.emit(h.ReplayerEvents.CustomEvent,b)};break;case h.EventType.Meta:d=function(){return f.emitter.emit(h.ReplayerEvents.Resize,{width:b.data.width,height:b.data.height})};break;case h.EventType.FullSnapshot:d=function(){f.rebuildFullSnapshot(b,c);f.iframe.contentWindow.scrollTo(b.data.initialOffset)};break;case h.EventType.IncrementalSnapshot:d=function(){var e;f.applyIncremental(b,c);if(!c&&
(b===f.nextUserInteractionEvent&&(f.nextUserInteractionEvent=null,f.backToNormal()),f.config.skipInactive&&!f.nextUserInteractionEvent)){try{for(var l=y(f.service.state.context.events),k=l.next();!k.done;k=l.next()){var m=k.value;if(!(m.timestamp<=b.timestamp)&&f.isUserInteraction(m)){m.delay-b.delay>1E4*f.speedService.state.context.timer.speed&&(f.nextUserInteractionEvent=m);break}}}catch(v){var r={error:v}}finally{try{k&&!k.done&&(e=l.return)&&e.call(l)}finally{if(r)throw r.error;}}f.nextUserInteractionEvent&&
(r={speed:Math.min(Math.round((f.nextUserInteractionEvent.delay-b.delay)/5E3),360)},f.speedService.send({type:"FAST_FORWARD",payload:r}),f.emitter.emit(h.ReplayerEvents.SkipStart,r))}}}return function(){d&&d();f.service.send({type:"CAST_EVENT",payload:{event:b}});if(b===f.service.state.context.events[f.service.state.context.events.length-1]){var e=function(){f.backToNormal();f.service.send("END");f.emitter.emit(h.ReplayerEvents.Finish)};b.type===h.EventType.IncrementalSnapshot&&b.data.source===h.IncrementalSource.MouseMove&&
b.data.positions.length?setTimeout(function(){e()},Math.max(0,-b.data.positions[0].timeOffset)):e()}}};a.prototype.rebuildFullSnapshot=function(b,c){void 0===c&&(c=!1);if(!this.iframe.contentDocument)return console.warn("Looks like your replayer has been destroyed.");Object.keys(this.legacy_missingNodeRetryMap).length&&console.warn("Found unresolved missing node map",this.legacy_missingNodeRetryMap);this.legacy_missingNodeRetryMap={};C.map=ib(b.data.node,{doc:this.iframe.contentDocument})[1];var f=
document.createElement("style"),d=this.iframe.contentDocument;d.documentElement.insertBefore(f,d.head);d=["iframe, ."+this.config.blockClass+" { background: #ccc }","noscript { display: none !important; }"].concat(this.config.insertStyleRules);this.config.pauseAnimation&&d.push("html.rrweb-paused * { animation-play-state: paused !important; }");this.service.state.matches("playing")||this.iframe.contentDocument.getElementsByTagName("html")[0].classList.add("rrweb-paused");for(var e=0;e<d.length;e++)f.sheet.insertRule(d[e],
e);this.emitter.emit(h.ReplayerEvents.FullsnapshotRebuilded,b);c||this.waitForStylesheetLoad();this.config.UNSAFE_replayCanvas&&this.preloadAllImages()};a.prototype.waitForStylesheetLoad=function(){var b=this,c,f=null===(c=this.iframe.contentDocument)||void 0===c?void 0:c.head;if(f){var d=new Set,e=this.service.state,l=function(){e=b.service.state};this.emitter.on(h.ReplayerEvents.Start,l);this.emitter.on(h.ReplayerEvents.Pause,l);var k=function(){b.emitter.off(h.ReplayerEvents.Start,l);b.emitter.off(h.ReplayerEvents.Pause,
l)};f.querySelectorAll('link[rel="stylesheet"]').forEach(function(r){r.sheet||(d.add(r),r.addEventListener("load",function(){d.delete(r);0===d.size&&-1!==m&&(e.matches("playing")&&b.play(b.getCurrentTime()),b.emitter.emit(h.ReplayerEvents.LoadStylesheetEnd),m&&window.clearTimeout(m),k())}))});if(0<d.size){this.service.send({type:"PAUSE"});this.emitter.emit(h.ReplayerEvents.LoadStylesheetStart);var m=window.setTimeout(function(){e.matches("playing")&&b.play(b.getCurrentTime());m=-1;k()},this.config.loadTimeout)}}};
a.prototype.preloadAllImages=function(){var b,c=this,f=this.service.state,d=function(){f=c.service.state};this.emitter.on(h.ReplayerEvents.Start,d);this.emitter.on(h.ReplayerEvents.Pause,d);var e=0,l=0;try{for(var k=y(this.service.state.context.events),m=k.next();!m.done;m=k.next()){var r=m.value;if(r.type===h.EventType.IncrementalSnapshot&&r.data.source===h.IncrementalSource.CanvasMutation&&"drawImage"===r.data.property&&"string"===typeof r.data.args[0]&&!this.imageMap.has(r)){e++;var v=document.createElement("img");
v.src=r.data.args[0];this.imageMap.set(r,v);v.onload=function(){l++;l===e&&(f.matches("playing")&&c.play(c.getCurrentTime()),c.emitter.off(h.ReplayerEvents.Start,d),c.emitter.off(h.ReplayerEvents.Pause,d))}}}}catch(u){var p={error:u}}finally{try{m&&!m.done&&(b=k.return)&&b.call(k)}finally{if(p)throw p.error;}}e!==l&&this.service.send({type:"PAUSE"})};a.prototype.applyIncremental=function(b,c){var f=this,d=b.data;switch(d.source){case h.IncrementalSource.Mutation:c&&(d.adds.forEach(function(g){return f.treeIndex.add(g)}),
d.texts.forEach(function(g){return f.treeIndex.text(g)}),d.attributes.forEach(function(g){return f.treeIndex.attribute(g)}),d.removes.forEach(function(g){return f.treeIndex.remove(g)}));this.applyMutation(d,c);break;case h.IncrementalSource.MouseMove:if(c){var e=d.positions[d.positions.length-1];this.moveAndHover(d,e.x,e.y,e.id)}else d.positions.forEach(function(g){f.timer.addAction({doAction:function(){f.moveAndHover(d,g.x,g.y,g.id)},delay:g.timeOffset+b.timestamp-f.service.state.context.baselineTime})}),
this.timer.addAction({doAction:function(){},delay:b.delay-(null===(e=d.positions[0])||void 0===e?NaN:e.timeOffset)});break;case h.IncrementalSource.MouseInteraction:if(-1===d.id)break;var l=new Event(h.MouseInteractions[d.type].toLowerCase());e=C.getNode(d.id);if(!e)return this.debugNodeNotFound(d,d.id);this.emitter.emit(h.ReplayerEvents.MouseInteraction,{type:d.type,target:e});var k=this.config.triggerFocus;switch(d.type){case h.MouseInteractions.Blur:"blur"in e&&e.blur();break;case h.MouseInteractions.Focus:k&&
e.focus&&e.focus({preventScroll:!0});break;case h.MouseInteractions.Click:case h.MouseInteractions.TouchStart:case h.MouseInteractions.TouchEnd:c||(this.moveAndHover(d,d.x,d.y,d.id),this.mouse.classList.remove("active"),void 0,this.mouse.classList.add("active"));break;default:e.dispatchEvent(l)}break;case h.IncrementalSource.Scroll:if(-1===d.id)break;if(c){this.treeIndex.scroll(d);break}this.applyScroll(d);break;case h.IncrementalSource.ViewportResize:this.emitter.emit(h.ReplayerEvents.Resize,{width:d.width,
height:d.height});break;case h.IncrementalSource.Input:if(-1===d.id)break;if(c){this.treeIndex.input(d);break}this.applyInput(d);break;case h.IncrementalSource.MediaInteraction:e=C.getNode(d.id);if(!e)return this.debugNodeNotFound(d,d.id);var m=e;try{d.type===na.Pause&&m.pause(),d.type===na.Play&&(m.readyState>=HTMLMediaElement.HAVE_CURRENT_DATA?m.play():m.addEventListener("canplay",function(){m.play()}))}catch(g){this.config.showWarning&&console.warn("Failed to replay media interactions: "+(g.message||
g))}break;case h.IncrementalSource.StyleSheetRule:e=C.getNode(d.id);if(!e)return this.debugNodeNotFound(d,d.id);c=e;l=e.parentNode;k=this.fragmentParentMap.has(l);var r=void 0;if(k){var v=this.fragmentParentMap.get(e.parentNode);r=document.createTextNode("");l.replaceChild(r,e);v.appendChild(e)}var p=c.sheet;d.adds&&d.adds.forEach(function(g){var n=g.rule;g=g.index;g=void 0===g?void 0:Math.min(g,p.rules.length);try{p.insertRule(n,g)}catch(t){}});d.removes&&d.removes.forEach(function(g){g=g.index;
try{p.deleteRule(g)}catch(n){}});k&&r&&l.replaceChild(e,r);break;case h.IncrementalSource.CanvasMutation:if(!this.config.UNSAFE_replayCanvas)break;e=C.getNode(d.id);if(!e)return this.debugNodeNotFound(d,d.id);try{l=e.getContext("2d"),d.setter?l[d.property]=d.args[0]:(k=l[d.property],"drawImage"===d.property&&"string"===typeof d.args[0]&&(r=this.imageMap.get(b),d.args[0]=r),k.apply(l,d.args))}catch(g){this.warnCanvasMutationFailed(d,d.id,g)}break;case h.IncrementalSource.Font:try{var u=new FontFace(d.family,
d.buffer?new Uint8Array(JSON.parse(d.fontSource)):d.fontSource,d.descriptors);null===(v=this.iframe.contentDocument)||void 0===v?void 0:v.fonts.add(u)}catch(g){this.config.showWarning&&console.warn(g)}}};a.prototype.applyMutation=function(b,c){var f,d,e=this;b.removes.forEach(function(n){var t=C.getNode(n.id);if(!t)return e.warnNodeNotFound(b,n.id);var A=C.getNode(n.parentId);if(!A)return e.warnNodeNotFound(b,n.parentId);C.removeNodeFromMap(t);A&&((n=e.fragmentParentMap.get(A))&&n.contains(t)?n.removeChild(t):
e.fragmentParentMap.has(t)?(n=e.fragmentParentMap.get(t),A.removeChild(n),e.fragmentParentMap.delete(t)):A.removeChild(t))});var l=P({},this.legacy_missingNodeRetryMap),k=[],m=function(n){if(!e.iframe.contentDocument)return console.warn("Looks like your replayer has been destroyed.");var t=C.getNode(n.parentId);if(!t)return k.push(n);var A=null;e.iframe.contentDocument.contains?A=e.iframe.contentDocument.contains(t):e.iframe.contentDocument.body.contains&&(A=e.iframe.contentDocument.body.contains(t));
if(c&&A){A=document.createDocumentFragment();C.map[n.parentId]=A;e.fragmentParentMap.set(A,t);for(e.storeState(t);t.firstChild;)A.appendChild(t.firstChild);t=A}var E=A=null;n.previousId&&(A=C.getNode(n.previousId));n.nextId&&(E=C.getNode(n.nextId));var H=null;n.nextId&&(H=C.getNode(n.nextId));H=null===n.nextId||void 0===n.nextId||-1===n.nextId||H?!1:!0;if(H)return k.push(n);H=ya(n.node,{doc:e.iframe.contentDocument,map:C.map,skipChild:!0,hackCss:!0});-1===n.previousId||-1===n.nextId?l[n.node.id]=
{node:H,mutation:n}:(A&&A.nextSibling&&A.nextSibling.parentNode?t.insertBefore(H,A.nextSibling):E&&E.parentNode?t.contains(E)?t.insertBefore(H,E):t.insertBefore(H,null):t.appendChild(H),(n.previousId||n.nextId)&&e.legacy_resolveMissingNode(l,t,H,n))};b.adds.forEach(function(n){m(n)});for(var r=Date.now();k.length;){var v=Oa(k);k.length=0;if(500<Date.now()-r){this.warn("Timeout in the loop, please check the resolve tree data:",v);break}try{for(var p=(f=void 0,y(v)),u=p.next();!u.done;u=p.next()){var g=
u.value;C.getNode(g.value.parentId)?Ea(g,function(n){m(n)}):this.debug("Drop resolve tree since there is no parent for the root node.",g)}}catch(n){f={error:n}}finally{try{u&&!u.done&&(d=p.return)&&d.call(p)}finally{if(f)throw f.error;}}}Object.keys(l).length&&Object.assign(this.legacy_missingNodeRetryMap,l);b.texts.forEach(function(n){var t=C.getNode(n.id);if(!t)return e.warnNodeNotFound(b,n.id);e.fragmentParentMap.has(t)&&(t=e.fragmentParentMap.get(t));t.textContent=n.value});b.attributes.forEach(function(n){var t=
C.getNode(n.id);if(!t)return e.warnNodeNotFound(b,n.id);e.fragmentParentMap.has(t)&&(t=e.fragmentParentMap.get(t));for(var A in n.attributes)if("string"===typeof A){var E=n.attributes[A];try{null!==E?t.setAttribute(A,E):t.removeAttribute(A)}catch(H){e.config.showWarning&&console.warn("An error occurred may due to the checkout feature.",H)}}})};a.prototype.applyScroll=function(b){var c=C.getNode(b.id);if(!c)return this.debugNodeNotFound(b,b.id);if(c===this.iframe.contentDocument)this.iframe.contentWindow.scrollTo({top:b.y,
left:b.x,behavior:"smooth"});else try{c.scrollTop=b.y,c.scrollLeft=b.x}catch(f){}};a.prototype.applyInput=function(b){var c=C.getNode(b.id);if(!c)return this.debugNodeNotFound(b,b.id);try{c.checked=b.isChecked,c.value=b.text}catch(f){}};a.prototype.legacy_resolveMissingNode=function(b,c,f,d){var e=d.previousId;d=d.nextId;e=e&&b[e];d=d&&b[d];if(e){var l=e.node;e=e.mutation;c.insertBefore(l,f);delete b[e.node.id];delete this.legacy_missingNodeRetryMap[e.node.id];(e.previousId||e.nextId)&&this.legacy_resolveMissingNode(b,
c,l,e)}d&&(l=d.node,e=d.mutation,c.insertBefore(l,f.nextSibling),delete b[e.node.id],delete this.legacy_missingNodeRetryMap[e.node.id],(e.previousId||e.nextId)&&this.legacy_resolveMissingNode(b,c,l,e))};a.prototype.moveAndHover=function(b,c,f,d){this.mouse.style.left=c+"px";this.mouse.style.top=f+"px";this.drawMouseTail({x:c,y:f});c=C.getNode(d);if(!c)return this.debugNodeNotFound(b,d);this.hoverElements(c)};a.prototype.drawMouseTail=function(b){var c=this;if(this.mouseTail){var f=!0===this.config.mouseTail?
Ja:Object.assign({},Ja,this.config.mouseTail),d=f.lineCap,e=f.lineWidth,l=f.strokeStyle;f=f.duration;var k=function(){if(c.mouseTail){var m=c.mouseTail.getContext("2d");m&&c.tailPositions.length&&(m.clearRect(0,0,c.mouseTail.width,c.mouseTail.height),m.beginPath(),m.lineWidth=e,m.lineCap=d,m.strokeStyle=l,m.moveTo(c.tailPositions[0].x,c.tailPositions[0].y),c.tailPositions.forEach(function(r){return m.lineTo(r.x,r.y)}),m.stroke())}};this.tailPositions.push(b);k();setTimeout(function(){c.tailPositions=
c.tailPositions.filter(function(m){return m!==b});k()},f)}};a.prototype.hoverElements=function(b){var c;for(null===(c=this.iframe.contentDocument)||void 0===c?void 0:c.querySelectorAll(".\\:hover").forEach(function(f){f.classList.remove(":hover")});b;)b.classList&&b.classList.add(":hover"),b=b.parentElement};a.prototype.isUserInteraction=function(b){return b.type!==h.EventType.IncrementalSnapshot?!1:b.data.source>h.IncrementalSource.Mutation&&b.data.source<=h.IncrementalSource.Input};a.prototype.backToNormal=
function(){this.nextUserInteractionEvent=null;this.speedService.state.matches("normal")||(this.speedService.send({type:"BACK_TO_NORMAL"}),this.emitter.emit(h.ReplayerEvents.SkipEnd,{speed:this.speedService.state.context.normalSpeed}))};a.prototype.storeState=function(b){var c;if(b&&b.nodeType===b.ELEMENT_NODE){(b.scrollLeft||b.scrollTop)&&this.elementStateMap.set(b,{scroll:[b.scrollLeft,b.scrollTop]});b=b.children;try{for(var f=y(Array.from(b)),d=f.next();!d.done;d=f.next())this.storeState(d.value)}catch(l){var e=
{error:l}}finally{try{d&&!d.done&&(c=f.return)&&c.call(f)}finally{if(e)throw e.error;}}}};a.prototype.restoreState=function(b){var c;if(b.nodeType===b.ELEMENT_NODE){if(this.elementStateMap.has(b)){var f=this.elementStateMap.get(b);f.scroll&&(b.scrollLeft=f.scroll[0],b.scrollTop=f.scroll[1]);this.elementStateMap.delete(b)}b=b.children;try{for(var d=y(Array.from(b)),e=d.next();!e.done;e=d.next())this.restoreState(e.value)}catch(k){var l={error:k}}finally{try{e&&!e.done&&(c=d.return)&&c.call(d)}finally{if(l)throw l.error;
}}}};a.prototype.warnNodeNotFound=function(b,c){this.warn("Node with id '"+c+"' not found in",b)};a.prototype.warnCanvasMutationFailed=function(b,c,f){this.warn("Has error on update canvas '"+c+"'",b,f)};a.prototype.debugNodeNotFound=function(b,c){this.debug("[replayer]","Node with id '"+c+"' not found in",b)};a.prototype.warn=function(){for(var b=[],c=0;c<arguments.length;c++)b[c]=arguments[c];this.config.showWarning&&console.warn.apply(console,x(["[replayer]"],b))};a.prototype.debug=function(){for(var b=
[],c=0;c<arguments.length;c++)b[c]=arguments[c];this.config.showDebug&&console.log.apply(console,x(["[replayer]"],b))};return a}();var Fb=sa.addCustomEvent,Gb=sa.freezePage;h.Replayer=Ia;h.addCustomEvent=Fb;h.freezePage=Gb;h.mirror=C;h.record=sa;h.utils=Bb;Object.defineProperty(h,"__esModule",{value:!0});return h}({}),rrwebSDK=function(h){var y=function(B){console.log("rrwebSDK : ",B)};y("init ...");"object"===typeof module&&"object"===typeof module.exports&&(y("init ... module mode ..."),module.exports=
h(y,rrweb));y("init ... ok");return h(y,rrweb)}(function(h,y){return function(B){var x={timer:null,events:[],stop:!0,debug:!1,rrwebStop:null},D={reportUrl:"https://www.yunbaoxiao.com.cn/recall",reportTimes:3,reportTimeout:0,notSupportInfo:"\u6d4f\u89c8\u5668\u7248\u672c\u8fc7\u4f4e\uff0c\u9700\u8981 IE11+ \u4ee5\u4e0a\u7248\u672c\u3002",notSupportEvent:null,sameOriginMerger:!1,signatureMode:1},F={recallCode:"",busCode:"",goodsCode:"",goodsVersion:""},T=function(z){x.debug&&console.log("rrwebSDK : ",
z)},Q=function(){var z=document.getElementById("__vconsole");z&&!z.classList.contains("rr-block")&&(z.classList.add("rr-block"),z.classList.add("rr-ignore"),h("vconsole shield."))},aa=function(z){var K=window.sessionStorage;switch(z){case void 0:return JSON.parse(K.getItem("rrwebsdk_cache"))||F;case null:K.removeItem("rrwebsdk_cache");break;default:K.setItem("rrwebsdk_cache",JSON.stringify(F))}},V=function(z){Q();T("report ...");if(x.events.length){var K=[].concat(x.events);x.events=[];var M=JSON.parse(JSON.stringify(F));
M.events=JSON.stringify({events:K});T(M);var W="",da;for(da in M)W+="&"+da+"="+encodeURIComponent(M[da]);W=W.substring(1);var R=new XMLHttpRequest;R.open("POST",D.reportUrl+"/api/events/report.shtml",!0);R.setRequestHeader("Content-Type","application/x-www-form-urlencoded");R.onreadystatechange=function(){4==R.readyState&&(200==R.status?(h("report ... ok ("+JSON.parse(R.responseText||"{}").message+")"),"function"==typeof z&&z(!0)):(h("report ... error ("+R.status+")"),x.events=[].concat(K,x.events),
"function"==typeof z&&z(!1)))};D.reportTimeout&&(R.timeout=1E3*D.reportTimeout);R.send(W)}else h("report ... ignore"),"function"==typeof z&&z(!0)},ha=function(){x.stop&&(x.stop=!1,x.rrwebStop=y.record({emit:function(z){x.stop?T("rr ... miss"):(T("rr ... +1 "+JSON.stringify(z)),x.events.push(z))}}),x.timer=setInterval(V,1E3*D.reportTimes),V())},ta=function(z,K){x.stop=!0;"function"==typeof x.rrwebStop&&x.rrwebStop();clearInterval(x.timer);K&&V(function(M){M&&"stop"==K&&aa(null);"function"==typeof z&&
z(M);h(K+" ... "+(M?"ok":"error"))})},ua=function(z){if("encode"==z)return T("token encode ..."),"rrwebsdk_token="+JSON.stringify(F).replace(/"/g,"@").replace(/:/g,"-").replace(/,/g,"_").replace(/[{}]/g,"");if("decode"==z){T("token decode ...");z=window.location.search.substring(1).split("&");for(var K="",M=0;M<z.length;M++){var W=z[M].split("=");if("rrwebsdk_token"==W[0]){K=W[1];break}}T("token decode ... : "+(K||"null"));if(K){z=JSON.parse("{"+K.replace(/@/g,'"').replace(/-/g,":").replace(/_/g,
",")+"}");for(var da in F)if(0>Object.keys(z).indexOf(da))return!1;return z}return!1}};this.report=function(z){var K=["goodsCode","goodsVersion","busCode"],M="goodsName orderNo policyNo applicantName idNo origin".split(" "),W=!1,da={},R;for(R in z)0<=K.indexOf(R)&&(F[R]=z[R],W=1),0<=K.concat(M).indexOf(R)&&(da[R]=z[R]);W&&aa(!0);"{}"!=JSON.stringify(da)&&x.events.push({type:"_customer_variable_",data:da})};this.start=function(z){h("start ...");x.stop?(F.recallCode="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx".replace(/x/g,
function(){return"0123456789abcdef".charAt(Math.floor(16*Math.random()))}),z&&z.constructor==Object&&z.goodsCode?(void 0==z.busCode&&(z.busCode=""),this.report(z)):aa(!0),setTimeout(ha,777),h("start ... ok")):h("start ... error (\u5df2\u5728\u5f55\u5236\u4e2d\uff0c\u82e5\u8981\u5f00\u59cb\u4e00\u4e2a\u65b0\u7684\u5f55\u5236\uff0c\u8bf7\u5148\u4f7f\u7528 stop() \u505c\u6b62\u65e7\u7684\u5f55\u5236)")};this.stop=function(z){h("stop ...");ta(z,"stop")};this.leaveReport=function(z){h("leaveReport ...");
x.stop?h("leaveReport ... error (\u672a\u5728\u5f55\u5236\u4e2d)"):ta(z,"leaveReport")};this.restoreReport=function(){h("restoreReport ...");if(x.stop){if(!F.recallCode){var z=ua("decode");if(z)F=z,aa(!0);else{h("restoreReport ... error (\u56de\u6eaf\u7801\u4e0d\u5b58\u5728\uff0c\u65e0\u6cd5\u7ee7\u7eed\u5f55\u5236)");return}}setTimeout(ha,777);h("restoreReport ... ok")}else h("restoreReport ... error (\u5df2\u5728\u5f55\u5236\u4e2d)")};this.open=function(z){h("open ...");var K=0>z.indexOf("?")?"?":
"&";window.location.href=z+K+ua("encode")};this.static=function(z){z&&(z.constructor==Array?z:[z]).forEach(function(K){if(K=document.querySelector(K))K.onload=function(){if("data:image"!=this.src.substring(0,10)){var M=document.createElement("canvas");M.width=this.width;M.height=this.height;M.getContext("2d").drawImage(this,0,0,this.width,this.height);this.src=M.toDataURL("image/png")}},K.onload()})};this.debug=function(z){h("debug ...");x.debug=!!z;h("debug ... "+(x.debug?"on":"off"))};this.config=
function(z,K){if(D.hasOwnProperty(z)){if(void 0==K)return D[z];D[z]=K}};this.version=function(){h("version 1.2.4 bate");return"1.2.4 bate"};h("instantiate ...");if(B)for(var J in D)void 0!==B[J]&&(D[J]=B[J]);window.MutationObserver?(window.__rrwebsdk_config=D,F=aa(),Q(),h("instantiate ... ok")):(D.notSupportEvent?D.notSupportEvent():(alert(D.notSupportInfo),window.history.back()),h("instantiate ... error"))}});